alphagov/asset-manager

bin/create_asset, bin/update_asset
2 scripts:
first: allows to upload a single file on asset-manager
second: allows to update a single file on asset-manager
Work required by this ticket:
https://www.pivotaltracker.com/story/show/94847618
=> Add scritps to manage assets

.dockerignore, Dockerfile, config/mongoid.yml
This allows this app to be built as part of a docker stack.
It's somewhat painful as clamav is a dependency, definitely welcome to suggestions if there's a better way to do that and/or if we can use clamav as an image dependency.
=> Setup dockerfile

spec/controllers/assets_controller_spec.rb, spec/controllers/media_controller_spec.rb, spec/lib/virus_scanner_spec.rb, spec/models/asset_spec.rb, spec/requests/asset_requests_spec.rb, spec/requests/media_requests_spec.rb, spec/requests/virus_scanning_spec.rb
I've done a bit of tidying up of the specs, e.g.
* Use `subject` or `let` vs instance variables
* Use `before` vs `before :each`
=> Make more idiomatic use of RSpec

README.md
I found it useful to use cURL to interact with the API. I hope these
examples make it easier for others to do the same.
=> Add API examples to the README

README.md, docs/migrating-assets-to-s3.md
I'm hoping we can keep this document up to date and to have it serve as
a single resource we can point people to when talking about the
migration of assets to S3.
=> Add an overview of the migration of assets to S3

docs/costing.md, docs/existing_assets.md
Add some documentation as per #103 and #104
=> Add some documentation

spec/models/asset_spec.rb
This should avoid problems like the one fixed in #124 happening again.
=> Add example to exercise S3Storage::Null#save

docs/migrating-assets-to-s3.md
So that it reflects our current approach.
=> Update migrating-assets-to-s3 doc

config/routes.rb
This is a more Rails-y approach.
=> Use resourceful route for assets#restore

README.md
This relates to functionality added in #210 and #228.
=> Add documentation for API endpoint for creating Whitehall assets

README.md
I've also made a few small changes to the existing API examples - see the commit notes for details.
Closes #223.
=> Add examples of how to use the API in the integration environment

README.md
This is just a small tweak to make it easier to copy and paste the code example into a terminal.
=> Improve documentation for manual testing in integration

README.md
I neglected to change this in #374.
=> Fix docs about testing in integration

app/controllers/assets_controller.rb, app/controllers/base_assets_controller.rb, app/controllers/media_controller.rb, app/controllers/whitehall_assets_controller.rb, lib/tasks/govuk_assets.rake, spec/controllers/assets_controller_spec.rb, spec/controllers/media_controller_spec.rb, spec/controllers/whitehall_assets_controller_spec.rb
Minor improvements:
* Add missing test coverage
* Normalize blank `Asset#redirect_url` values
* Add `redirect_url` behaviour for Mainstream as well as Whitehall assets
=> Improvements for redirect_url functionality

app/controllers/application_controller.rb, app/controllers/base_assets_controller.rb, app/controllers/media_controller.rb, app/controllers/whitehall_media_controller.rb, lib/cache_control_configuration.rb, spec/lib/cache_control_configuration_spec.rb
This fixes a minor bug in the existing code. The bug hadn't led to any incorrect external behaviour, but it meant that the code was confusing and could've led to unintended incorrect external behaviour in the future.
I've also reduced the amount of duplication slightly which will make it easier to apply some upcoming changes.
=> Improvements to cache control

app/models/asset.rb, app/models/whitehall_asset.rb, spec/models/asset_spec.rb
https://trello.com/c/VubcGtSx/343-investigate-asset-manager-default-scopes
=> Fix typo in scope

lib/tasks/govuk_assets.rake
This is probably useful, and is an indirect stepping stone to HMRC assets
=> Add a rake task to create a whitehall asset

app/controllers/media_controller.rb
Kind of surprised that the tests I added in #610 passed.  I based them on other tests for things with invalid filenames.
=> Use user_signed_in?

app/controllers/media_controller.rb, spec/requests/media_requests_spec.rb
This fixes an issue when viewing an asset that is access limited and the user is logged in and supplies a bypass id. The previous logic would not check the bypass id if the user was logged in and unsuccessfully try to re-authenticate the user. This fixes the logic to first check if a user has a correct bypass id, then if the authenticate the user and then check if the user is permitted in the access limits.
=> Fix bug when viewing access limited asset

.rubocop.yml, app/controllers/assets_controller.rb, app/models/asset.rb, app/models/user.rb, lib/cli.rb, lib/tasks/db.rake, spec/controllers/assets_controller_spec.rb, spec/controllers/media_controller_spec.rb, spec/controllers/whitehall_media_controller_spec.rb, spec/factories/factories.rb, spec/models/asset_spec.rb, spec/models/whitehall_asset_spec.rb, spec/rails_helper.rb, spec/requests/media_requests_spec.rb, spec/requests/whitehall_media_requests_spec.rb
trello: https://trello.com/c/Lijki8aj/1584-3-enable-rails-rubocop-rules-via-rubocop-govuk-on-all-our-rails-apps
=> Enable rails-specific rules for rubocop-govuk

lib/tasks/assets.rake
https://trello.com/c/HfMApI04/947-make-it-easier-to-cleanup-stray-whitehall-assets
Please see the commits for more details.
=> Add whitehall-specific tasks to avoid SSH

Gemfile, Gemfile.lock
Version 0.3.6 has been yanked.
---
[Trello card](https://trello.com/c/3EKxoz27/1123-the-mimemagic-situation)
=> Switch to my fork of mimemagic-0.3.7

config/routes.rb
[Trello card](https://trello.com/c/tl6RV1el/723-improve-govuk-healthchecks)
=> Fix a couple of errors in the readiness healthcheck

.dockerignore, Dockerfile
=> Updating Dockerfile to rm app/tmp on the last step in Builder stage.

app/controllers/media_controller.rb, spec/controllers/media_controller_spec.rb
We are currently redirecting to `draft-assets.publishing.service.gov.uk` when a draft asset is requested by an internal request made by another application (i.e. at the hostname of `asset-manager` on our internal infrastructure).
This means that Frontend (when rendering CSV previews), attempts to follow the redirect to the draft asset, resulting in an error as it is not able to authenticate itself at that URL.  Additionally, Frontend already handles the redirect to the draft host.
Therefore removing this redirect when a draft asset is requested internally by another application.  Authentication still exists, so the requesting application must still have a suitable bearer token.
This application is owned by the publishing platform team. Please let us know in #govuk-publishing-platform when …
=> Do not redirect to draft asset host for internal requests
