alphagov/asset-manager

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
Without this, requests to assets.digital.cabinet.office.gov.uk are redirected to assets-origin.production.alphagov.co.uk, which is not publically available.
> Use a relative URL for redirection

- LICENCE
- README.md
It took me a while to understand why I could see my uploaded assets in dev environtment, so here's an improved readme that should save time for other developers looking at this.
I've also added a MIT licence because this repo didn't seem to have any.
In addition to this PR the repo could benefit from adding a one line description on GitHub (someone with admin access to the repo should be able to do that)
> Improve readme

- README.md
(was a POST, but that's not what routes.rb thinks)
> README asset update method changed to PUT

- Gemfile
- Gemfile.lock
- app/controllers/assets_controller.rb
- app/models/asset.rb
- config/routes.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/factories/factories.rb
- spec/models/asset_spec.rb
Part of https://trello.com/c/zLrCEavw/263-delete-attachments-feature-medium
Adds the route DELETE #destroy for assets.
Assets are soft deleted using the `mongoid_paranoia` gem. Requests to show a soft deleted asset or download media belonging to a soft deleted asset will respond with 404 as this is the default behaviour for rescued `Mongoid::Errors::DocumentNotFound` [in the application controller](https://github.com/alphagov/asset-manager/blob/master/app/controllers/application_controller.rb#L10).
> Soft delete assets

- app/controllers/assets_controller.rb
- config/routes.rb
- spec/controllers/assets_controller_spec.rb
- spec/models/asset_spec.rb
- spec/requests/asset_requests_spec.rb
Part of: https://trello.com/c/Vn2SpooI/279-document-attachments-still-visible-when-document-is-unpublished-large
Soft deleted assets can be restored via the `/assets/:id/restore` route.
This allows withdrawn content with soft deleted assets to be unwithdrawn and their assets restored.
> Restore assets

- config/initializers/airbrake.rb
- config/initializers/gds-sso.rb
This sets up env vars so they can be used instead of them being replaced at deploy time.
This should not be merged until the following are merged and deployed:
> Set up env vars for secrets

- Dockerfile
This allows less code needed in a docker-compose in most cases. Also
changed the db name to not specify an environment.
> More defaults in Dockerfile

- Gemfile
- Gemfile.lock
- config/initializers/airbrake.rb
This allows the errbit configuration to be tailored more to the environment, which is useful for end to end tests.
> Use plek for errbit

- Gemfile
- Gemfile.lock
- app/controllers/media_controller.rb
- app/models/asset.rb
- config/initializers/aws.rb
- lib/s3_storage.rb
- lib/services.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
- spec/support/s3_storage.rb
This is the first step in changing the Asset Manager to store its assets in and serve its assets from AWS S3, i.e. to avoid using NFS.
This PR means that whenever an asset is successfully virus scanned a new asynchronous job is kicked off to upload the asset to S3. The fact that it's a separate job should mean that the current external behaviour is unaffected; the assets are still stored on NFS as before.
Also if `stream_from_s3=true` is added to the query string of the public URL for an asset, then the asset will be streamed from S3 via the Asset Manager app. The default behaviour is unaffected.
Serving assets through the Rails app and not using `X-Sendfile` and nginx is naïve and may well not be practical for production use, but deploying these changes will allow us to check that we …
> Store assets on S3 as well as NFS and optionally serve from S3 on public URLs

- README.md
- app/controllers/media_controller.rb
- config/initializers/aws.rb
- spec/controllers/media_controller_spec.rb
This allows us to make streaming from S3 the default behaviour in a given environment based on the presence of the new `STREAM_ALL_ASSETS_FROM_S3` environment variable.
I've also added some documentation about the whole "Assets on S3" functionality, mainly in order to document the various environment variables.
Note that this is based on #84 and includes a squash commit of those changes which will be removed before merging.
> Enable "stream from S3" functionality via an environment variable

- spec/support/cloud_storage.rb
It appears as if this `before` block was never getting executed, probably because the metadata value was `nil` rather than `false` by default.
This had gone unnoticed, because as long as the `AWS_S3_BUCKET_NAME` environment variable is not set, `Services.cloud_storage` will return an instance of `S3Storage::Null` which does not attempt to connect to AWS for real.
However, if this environment variable is set, then `Services.cloud_storage` will return an instance of `S3Storage` and this instance will be memo-ized.
When a couple of the "Media requests" spec examples run, they rely on setting the bucket name to `nil` supposedly to get `Services.cloud_storage` to return an instance of `S3Storage::Null`,
but, if the instance of `S3Storage` has been memo-ized as the result of a previous spec …
> Fix stubbing of Services.cloud_storage

- app/controllers/application_controller.rb
- app/controllers/media_controller.rb
- app/models/asset.rb
- config/application.rb
- config/initializers/aws.rb
- config/initializers/cache_control.rb
- lib/cache_control_configuration.rb
- lib/s3_storage.rb
- lib/services.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/cache_control_configuration_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
- spec/requests/media_requests_spec.rb
We want to be able to redirect Asset Manager requests to the assets stored in an S3 bucket. However, we want as much of the externally-visible behaviour to remain the same and so we need to set the 'Cache-Control' header to the same value as in `MediaController#download`, i.e. the value generated by [`ActionController::ConditionalGet#expires_in`][1] using `ApplicationController#set_expiry`.
Closes #96.
[1]: http://api.rubyonrails.org/v4.2.7.1/classes/ActionController/ConditionalGet.html#method-i-expires_in
> Add Cache-Control header to S3 object

- app/controllers/media_controller.rb
- app/models/asset.rb
- config/application.rb
- config/initializers/content_disposition.rb
- lib/content_disposition_configuration.rb
- spec/lib/content_disposition_configuration_spec.rb
- spec/models/asset_spec.rb
We want to be able to redirect Asset Manager requests to the assets stored in an S3 bucket. However, we want as much of the externally-visible behaviour to remain the same and so we need to set the 'Content-Disposition' header to the same value as in `MediaController#download`, i.e. the value generated by [`ActionController::DataStreaming#send_data`][1] or [`ActionController::DataStreaming#send_file`][2].
Note that his is based on the work in [Add Cache-Control header to S3 object][3], so it's probably worth waiting until that is merged before reviewing this.
Closes #95.
[1]: http://api.rubyonrails.org/v4.2.7.1/classes/ActionController/DataStreaming.html#method-i-send_data
[2]: http://api.rubyonrails.org/v4.2.7.1/classes/ActionController/DataStreaming.html#method-i-send_file
[3]: …
> Add Content-Disposition header to S3 object

- README.md
- app/controllers/media_controller.rb
- config/application.rb
- config/initializers/aws.rb
- lib/s3_storage.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage_spec.rb
We're currently experimenting with different ways to serve assets and adding this optional behaviour makes it possible to have the Asset Manager *redirect* public requests for assets to S3 rather than serving them from the (NFS) filesystem or streaming them from S3 through the app.
The new behaviour is not enabled by default and can be enabled for a single request using a query string parameter or for all requests in an environment by setting an environment variable. See the changes in the `README` for details.
Eventually we're probably going to want to use a "virtual host" style URL for the assets on S3, but this will require us to setup a DNS CNAME for an appropriate sub-domain of gov.uk and setup a bucket with the bucket name matching the fully-qualified domain name. To make it …
> Optionally redirect public asset requests to S3

- lib/s3_storage.rb
This resolves an argument error when `S3Storage::Null#save` gets called with 2 arguments per usage in https://github.com/alphagov/asset-manager/blob/master/app/models/asset.rb#L74
We see a few of these errors come through with the [Publishing E2E Tests](https://github.com/alphagov/publishing-e2e-tests) each time it runs.
Eg
```
timestamp: 2017-08-10 15:06:48 +0000
<?xml version="1.0" encoding="UTF-8"?>
<notice version="2.4">
<api-key>1</api-key>
<notifier>
<name>Airbrake Notifier</name>
<version>4.0.0</version>
<url>https://github.com/airbrake/airbrake</url>
</notifier>
<error>
<class>ArgumentError</class>
<message>ArgumentError: wrong number of arguments (2 for 1)</message>
<backtrace>
<line number="7" file="[PROJECT_ROOT]/lib/s3_storage.rb" method="save"/>
<line number="74" …
```
> Add missing 2nd argument to S3Storage::Null#save

- README.md
This was missing from the API docs and examples.
Note that these methods have already been [documented in the gds-api-adapters Gem][1].
[1]:
https://github.com/alphagov/gds-api-adapters/blob/6984336dc73d07a44d409ba138ae7e10d83148d2/lib/gds_api/asset_manager.rb#L94-L138
> Add info about destroy/restore endpoints to README

- Gemfile.lock
I ran the following command:
bundle update origin --conservative
My motivation for doing this was that I was seeing the following error when trying to upgrade unrelated gems:
Bundler could not find compatible versions for gem "origin":
In snapshot (Gemfile.lock):
origin (= 2.1.1)
In Gemfile:
mongoid (~> 5.0) was resolved to 5.2.1, which depends on
origin (~> 2.3)
This seems to suggest that the `origin` gem was locked at a version which was incompatible with the locked version of the `mongoid` gem. I'm guessing that the `Gemfile.lock` was edited by hand and left in an inconsistent state, so although `bundle install` worked OK, `bundle update` did not. This commit should fix that problem.
> Conservative upgrade of origin gem (fix inconsistent Gemfile.lock)

- app/models/asset.rb
- spec/models/asset_spec.rb
- spec/support/file_helpers.rb
Previously a virus scan was only triggered if the file had "changed" according to [`ActiveModel::Dirty`][1]. However, this seemed to have been based on whether the filename of the file had changed rather than whether the content had changed which seems to be the more relevant issue. This meant that (as described in #72) it was possible to update an existing asset with a file having the same name, but different content and for the asset to remain in the "clean" state. This seemed like a security hole.
Initially I investigated triggering a virus scan when the file *content* changed. However, this proved awkward due to the way both `state_machines` and `carrierwave` gems work. So after discussion with @chrisroos & @chrislo, I decided to trigger a virus scan whenever the `Asset#file` …
> Always virus scan uploaded files

- app/controllers/media_controller.rb
- lib/s3_storage.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage_spec.rb
This complements [the change in the asset-manager nginx config][1].
The app sets the `X-Accel-Redirect` header to instruct nginx to proxy
the request for an asset to S3.
We're generating a presigned URL for the assets on S3 so that we can
avoid making them publicly accessible. The presigned URL is valid for 1
minute which should be enough time for nginx to use the URL to make the
request.
[1]: https://github.com/alphagov/govuk-puppet/pull/6280
> Optionally instruct nginx to proxy assets from S3

- Gemfile
- Gemfile.lock
I changed the constraint in the `Gemfile` from `~> 4.0.0` to `~> 4.0` and ran the following command:
bundle update --conservative airbrake
My main motivation for doing this is so that `airbrake` [reports `ActionController::BadRequest` exceptions correctly][1].
However, I've chosen to upgrade to the latest 4.x version, because that should include other bug fixes without breaking compatibility with `errbit`. I'm pretty sure this is safe to do, because I can see that a bunch of other GOV.UK apps are using this version of `airbrake` in production, e.g.
* `calculators`
* `hmrc-manuals-api`
* `manuals-publisher`
* `publisher`
* `rummager`
Closes #122.
[1]: https://github.com/airbrake/airbrake/pull/271
> Upgrade airbrake gem v4.0.0 -> v4.3.8

- config/initializers/airbrake.rb
We've seen a bunch of requests in production which have a path with invalid string encoding. This results in an `ActionController::BadRequest` exception being raised. Rails handles this exception and responds with a 400 Bad Request which seems correct. However, the exception is unnecessarily reported to Errbit.
I did consider only reporting these exceptions when they had a specific exception message, but it turns out that in this case there is no exception message, so it's difficult to be more specific.
However, I'm pretty convinced that ignoring all such exceptions is safe to do given that a bunch of other exceptions that [Rails handles by default][1] are [ignored by default by Airbrake][2]. Indeed there is a case to be made that we should bring the Airbrake list into line with the Rails …
> Ignore ActionController::BadRequest exceptions in Airbrake

- app/models/asset.rb
- config/application.rb
- config/initializers/content_type.rb
- spec/models/asset_spec.rb
We're currently thinking about either redirecting Asset Manager requests to S3 or proxying them to S3. In either case, we want to include the same response headers to keep the externally visible behaviour unchanged.
We've already added Cache-Control and Content-Disposition headers in previous pull requests (#109 & #111) and this commit adds Content-Type based on the [same logic that `ActionController::DataStreaming#send_file` uses][1].
I've set `AssetManager.default_content_type` to [the default value used by Rails][2] to ensure that the existing `send_file` behaviour and any new behaviour which relies on assets being downloaded from S3 are kept in sync.
Closes #130.
[1]: https://github.com/rails/rails/blob/v4.2.7.1/actionpack/lib/action_controller/metal/data_streaming.rb#L146
[2]: …
> Set Content-Type when uploading asset to S3

- docs/existing_assets.md
This table shows the frequency of occurrence of different file
extensions in the asset manager NFS directory which is useful when
considering whether or not to compress stored assets.
> Add a table of file extension frequencies to docs

- app/models/asset.rb
We were seeing the following warning in the Rails log:
Overwriting existing field file in class Asset
This was happening because the [uploader declaration was also declaring the `file` field][1]:
mount_uploader :file, AssetUploader
The latter set the field type to be `Object` whereas the former set the field type to `String`. However the latter took precedence anyway and so removing the former has no net effect.
Fixes #69.
[1]: https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/v0.8.1/lib/carrierwave/mongoid.rb#L15
> Avoid Mongoid warning about overwriting Asset field

- README.md
- app/controllers/media_controller.rb
- config/application.rb
- config/initializers/aws.rb
- config/initializers/features.rb
- spec/controllers/media_controller_spec.rb
- spec/requests/media_requests_spec.rb
The motivation behind this commit is to allow us to incrementally roll-out the use of the proxying to S3 via Nginx mechanism. Although we've done a bunch of performance testing and analysis of the production logs, it's difficult to be certain that the production stack will be able to handle all its usual traffic when this mechanism is enabled. By only enabling it gradually we hope to observe any problems before they become catastrophic.
The `PROXY_ALL_ASSET_REQUESTS_TO_S3_VIA_NGINX` environment variable has been renamed to `PROXY_PERCENTAGE_OF_ASSET_REQUESTS_TO_S3_VIA_NGINX` and this should be set to an integer value between 0 and 100. We will need to set appropriate values for each environment via `govuk-puppet`.
This addresses the Asset Manager aspect of #151, but we will need to set …
> Allow a percentage of traffic to be proxied to S3 via Nginx

- app/controllers/media_controller.rb
- app/models/asset.rb
- spec/controllers/media_controller_spec.rb
- spec/models/asset_spec.rb
We're planning to gradually rollout the implementation whereby the Rails app instructs Nginx to proxy asset requests to S3. The current default implementation is for the Rails app to instruct Nginx to serve the asset files from NFS. In this implementation Nginx is automatically adding an ETag and a Last-Modified header.
When we switch to proxying the asset requests to S3, we want to ensure these response headers are the same for a given asset file in order to avoid unnecessary cache invalidation and therefore extra load which will make it hard to discriminate between changes in performance due to the change in implementation versus changes in performance due to a reduction in caching.
This commit changes the Rails app so that it calculates the ETag and Last-Modified values based on the …
> Send ETag & Last-Modified response headers when proxying to S3 via Nginx

- app/controllers/media_controller.rb
- app/models/asset.rb
- spec/controllers/media_controller_spec.rb
- spec/models/asset_spec.rb
And stop setting them on the S3 object.
Prior to this commit, the Rails app was both setting a `Cache-Control` response header on the S3 object *and* sending a `Cache-Control` response header in the response to Nginx instructing it to proxy the request to S3. Thus the user was receiving two duplicate `Cache-Control` headers. Although the values would have been the same, we want to avoid confusion and/or unexpected behaviour.
After this commit we no longer set the `Cache-Control`, `Content-Disposition`, or `Content-Type` headers on the S3 object. Instead the Rails app sends these headers to Nginx. We plan to update the Nginx configuration in a separate pull request against govuk-puppet in order to ensure the headers from Rails are added to the proxied response.
In #158 we considered …
> Send more response headers when proxying to S3 via Nginx

- README.md
- config/initializers/aws.rb
Supersedes #159.
The app will now fail fast with a KeyError if the `AWS_S3_BUCKET_NAME` environment variable is not set in the production environment.
If the environment variable is not set in the development environment then a "null object" version of the `S3Storage` class is used so that uploads are a no-op. However, note that asset requests using the `proxy_to_s3_via_nginx` option will fail with a 500 Server Error via the `S3Storage::NotConfiguredError` exception.
In the test environment, by default the `Services.cloud_storage` method returns an RSpec stub. This can be overridden by setting `disable_cloud_storage_stub: true` in the RSpec metadata for an example, context, or spec.
I've updated the README to reflect these changes and indicate which environment variables are required in …
> Fail fast if S3 bucket name is not configured in production

- config/initializers/aws.rb
I was seeing the following locally:
* Layout/IndentationWidth
* Layout/ElseAlignment
* Lint/EndAlignment
For some reason these were not picked up by the Jenkins CI build of the master branch. I plan to investigate why this didn't happen separately.
> Fix some Rubocop offences & warnings in AWS config

- app/models/asset.rb
- lib/data_migration.rb
- lib/s3_storage.rb
- lib/tasks/add_uuid_to_assets.rake
- spec/lib/data_migration_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
Before this PR we were using Asset#id to generate the key used to store the asset in the S3 bucket. We feel that this couples the storage of the assets a little too closely to Mongo and its mechanism for generating ids and may make it difficult to change database technology in the future. In addition it overloads further the _id field in the asset document which is already used to generate URLs in the API response and filenames for NFS storage.
Instead we'll use a UUID as the object key, generated using Ruby's RFC 4122[1] compliant SecureRandom#uuid. This means that the key generation is in the application code and decoupled from the database.
At this stage we are not considering changing how assets are stored on the NFS filesystem, or the object ID created for them in the JSON response. …
> Use a generated UUID for storing Assets on S3

- app/controllers/media_controller.rb
- lib/s3_storage.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage_spec.rb
Previously we were assuming all requests handled by `MediaController#download` were HTTP GET requests, but HEAD requests are also possible. When proxying asset requests to S3 via Nginx we were then generating S3 URL signatures based on this assumption, but these signatures were invalid when used in the subsequent HEAD request by Nginx and led to a 403 Forbidden response being sent to the client.
This commit supplies the HTTP method to the code which generates the pre-signed S3 URLs and hence HEAD requests for assets now work OK when proxying to S3 via Nginx.
Fixes #169.
> Specify appropriate HTTP method when pre-signing S3 URLs

- app/models/asset.rb
- spec/models/asset_spec.rb
Prior to this commit, `Asset#content_type` would return an empty string
if the file extension wasn't found by `Mime::Type.lookup`. This meant
that the `Content-Type` response header was also being set to an empty
string. Something else in the Rails stack (presumably some middleware)
was then replacing this empty string with "\*/\*; charset=utf-8". The
effect of this was that the `Content-Type` response header for files
with unrecognised mime types would be 'application/octet-stream' when
serving the file from the disk and '\*/\*; charset=utf-8' when serving the
file from S3.
This commit ensures we send the default content type
('application/octet-stream') for files with unrecognised mime types when
proxying requests to S3.
Note that `Mime::Type.lookup_by_extension(nil)` returns the same …
> Avoid sending empty Content-Type header when proxying to S3

- app/models/asset.rb
- lib/s3_storage.rb
- lib/tasks/s3.rake
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
This PR changes the existing upload mechanism so that we store an MD5 digest on each asset in S3 which means we can do a HEAD request to check whether an up-to-date copy of the asset already exists on S3 and thus avoid having to upload it again. See the commit note with subject "Do not upload asset to S3 if file content is identical" for further details on why we chose to do it this way.
This PR also adds a rake task (`s3:upload_all_clean_assets`) to upload existing clean assets to S3 via a low priority `Delayed::Job` per asset. The rake task accepts a `percentage` argument which sets the probability that an asset is uploaded - the idea is that we can use this to test the task with a random subset of assets. The improved upload mechanism mentioned above means it's OK to run the rake task …
> Add a rake task to allow uploading existing assets to S3

- .dockerignore
These scripts were removed in [this commit][1].
[1]: https://github.com/alphagov/asset-manager/commit/74af146d48fbbd98595df5d3f000899f77d2aee9
> Remove jenkins scripts from dockerignore file

- Dockerfile
This brings them into line with the ones specified in the `.ruby-version` file and the `Gemfile.lock`.
I built an image from the `Dockerfile` and ran it in a container to check the changes had taken effect:
```
root@ac73aeccb4e9:/app# ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
root@ac73aeccb4e9:/app# bundler -v
Bundler version 1.14.5
```
Closes #143.
> Update Ruby & Bundler versions in Dockerfile

- README.md
- app/controllers/media_controller.rb
- config/application.rb
- config/initializers/features.rb
- spec/controllers/media_controller_spec.rb
- spec/requests/media_requests_spec.rb
This has been superseded by the better-performing functionality which proxies to S3 via Nginx.
> Remove ability to proxy to S3 via Rails

- app/helpers/application_helper.rb
- app/presenters/asset_presenter.rb
- spec/controllers/media_controller_spec.rb
- spec/presenters/asset_presenter_spec.rb
By making use of methods that have been added to `Asset`, e.g. `Asset#content_type` and `Asset#filename`.
> Reduce duplication in asset-related logic

- config/application.rb
We're going to want to use this for the `thumbnail-placeholder.png` image which we're going to move across from Whitehall.
We've set the assets prefix in order to: (a) avoid a conflict with the `/assets` route defined within Asset Manager for its API endpoint; and (b) conform with the approach taken by other apps like Static to allow routing [via the Nginx configuration for the assets-origin host][1].
Note that we don't need any of `sass-rails`, `coffee-rails` and `uglifier` gems, because we only need to serve images.
[1]:
https://github.com/alphagov/govuk-puppet/blob/994d5424c7e4e28e903039f9f603e8d345b4f01d/hieradata/common.yaml#L1545-L1566
> Enable Rails asset pipeline

- .rubocop_todo.yml
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/asset.rb
- app/models/whitehall_asset.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/factories/factories.rb
- spec/models/asset_spec.rb
- spec/models/whitehall_asset_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
This introduces a `WhitehallAsset` subclass of `Asset` and pulls down the `legacy_url_path` attribute from `Asset` to `WhitehallAsset` along with related behaviour. The validation for `WhitehallAsset` is then modified to require the presence of the `legacy_url_path` attribute. The effect of this will be to respond with an error if no `legacy_url_path` is supplied to `WhitehallAssetsController#create`.
> Require legacy_url_path when creating Whitehall asset

- .rubocop_todo.yml
- app/models/asset.rb
- app/workers/save_to_cloud_storage_worker.rb
- spec/models/asset_spec.rb
- spec/workers/save_to_cloud_storage_worker_spec.rb
This PR moves the uploading of assets to S3 from a delayed_job worker to a sidekiq worker. 
There is a reference to `asset-manager/lib/tasks/s3.rake` to `save_to_cloud_storage`. Looking at this rake task, I think it should be removed as it has already been run (and if we need it again it'll be in a different form) so I haven't converted it. I've [opened a new PR](https://github.com/alphagov/asset-manager/pull/222) to do that. 
Contributes to: #179
> Migrate S3 upload worker to sidekiq

- Gemfile.lock
This app [currently uses Ruby v2.3.1][1] which means it [will run with v1.15.1 of bundler in production][2]. This commit brings the version listed in `Gemfile.lock` into line.
[1]:
https://github.com/alphagov/asset-manager/blob/00ecdd6f62bdd479db8339c1c25d17fc51822537/.ruby-version#L1
[2]:
https://github.com/alphagov/govuk-puppet/blob/c54ffa3132b5ead484d9ac78a36813760a89d6e5/modules/govuk_rbenv/manifests/all.pp#L55-L57
> Update BUNDLED WITH in Gemfile.lock

- app/models/asset.rb
- lib/tasks/assets.rake
- spec/models/asset_spec.rb
Previously the `Asset` attribute methods `#etag`, `#last_modified` and `#md5_hexdigest` generated a value from the underlying file metadata. However, we want to remove dependencies on the "local" (NFS) filesystem so that it can be removed in preference to the S3 file store. To this end, I've made the following changes:
* For new assets, the attribute values generated from the underlying file metadata are stored in the database.
* For existing assets, I've created the `assets:store_values_generated_from_file_metadata` rake task so we can use it to store the values generated from the underlying file metadata.
* For all assets, the attribute methods now return the value in database in preference to generating a value from the underlying metadata. However, for the time being they will …
> Store asset attributes generated from file metadata in database

- Dockerfile
This project is now dependent on Redis since Sidekiq was introduced,
this adds in a default value for the hostname.
> Add default REDIS_HOST env var to dockerfile

- README.md
- app/controllers/whitehall_assets_controller.rb
- app/models/whitehall_asset.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/factories/factories.rb
- spec/models/whitehall_asset_spec.rb
Add optional `legacy_etag` & `legacy_last_modified` parameters for the API endpoint which allows creation of Whitehall assets. We're going to need these when we move existing Whitehall assets to Asset Manager in order to avoid wholesale cache invalidation. See #234 for more details.
I've chosen to use `legacy_xxx` vs just `xxx` as the parameter names, because once we've moved the existing Whitehall assets to Asset Manager they will become redundant. Hopefully the names will also discourage anyone from using the parameters in any of the other publishing apps.
I've aliased `WhitehallAsset#legacy_xxx=` to `Asset#xxx=` partly in recognition that we'll only ever need to set `Asset#xxx` via the API when we move existing Whitehall assets to Asset Manager and partly to keep the code as simple as …
> Allow etag and last_modified to be specified when creating Whitehall assets via API

- lib/s3_storage.rb
- spec/lib/s3_storage_spec.rb
The `S3Storage::Null` class had got out of sync with `S3Storage`. I've fixed this and added an example to ensure it doesn't happen again. I've also extracted the exception message into a constant to avoid duplication.
> Ensure S3Storage::Null object implements all public methods of S3Storage

- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- config/application.rb
- config/initializers/frame_options.rb
- spec/requests/media_requests_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
Currently the `X-Frame-Options` header is set to `DENY` for Mainstream assets [via the Nginx config for the `asset-manager` host][1]. For Whitehall assets this header is set to the value in the response from the Whitehall Rails app [by the Nginx config for the `whitehall-admin` host][2]. [By default Rails sets this value to `SAMEORIGIN`][3] and the default is not overridden in the Whitehall app config.
We're planning to serve Whitehall assets from Asset Manager. This PR changes the Rails app to set the response header explicitly to "DENY" for Mainstream assets and to "SAMEORIGIN" for Whitehall assets. Once this change is deployed we will be able to change the Nginx config for the `asset-manager` host to [respect the value in the response from the Asset Manager Rails app][4] in order to …
> Set X-Frame-Options response header explicitly in Rails app

- lib/tasks/assets.rake
This makes some improvements to the `assets:store_values_generated_from_file_metadata` Rake task (added in #240) based on my experience of running it in integration:
* Use `Asset#set` vs `Asset#update_attributes!` to avoid unnecessarily running validation & callbacks
* Add debug output to give an indication of progress and check that all assets have file metadata attributes set
The Rake task takes about 15 mins to run in integration - I'm hopefully it will run a bit faster in production.
> Improvements to assets:store_values_generated_from_file_metadata Rake task

- lib/tasks/assets.rake
So that the progress output is visible when running from Jenkins.
> Flush stdout in Rake task to store asset file metadata

- app/workers/asset_file_metadata_worker.rb
- config/sidekiq.yml
- lib/tasks/assets.rake
- lib/tasks/govuk_assets.rake
This PR contains further improvement to the `assets:store_values_generated_from_file_metadata` Rake task based on my recent experience of running it in staging.
In staging @thomasleese & I saw a problem running the Rake task in which the `each` block was executed more times than the number of assets in the database, i.e. the percent complete went well over 100%. I suspect this was caused by a problem with the MongoDB cursor somehow being reset within the `each` block, perhaps due to a timeout.
This PR changes the Rake task so it just queues up jobs to be executed by a worker class at a lower priority than the jobs used by the application in normal operation. This way the execution of the `each` block will be less than 1 min vs more than 15 mins. I'm hopeful that this will avoid the cursor …
> Use Sidekiq worker to store values generated from file metadata on assets

- lib/tasks/govuk_assets.rake
I've continued to see problems with the progress indicator going over 100% even since converting the `govuk_assets:store_values_generated_from_file_metadata` Rake task to use Sidekiq to queue the work. By obtaining *all* the asset IDs in a single fast-running query I'm hoping to avoid any problems with Mongoid cursors, which I think is at the root of the problems I've been seeing.
Prior to opening this PR, I've deployed this branch to integration and run the Rake task with the following output:
```
$ govuk_setenv asset-manager bundle exec rake govuk_assets:store_values_generated_from_file_metadata
I, [2017-10-05T14:37:03.276150 #17598]  INFO -- sentry: ** [Raven] Raven 2.6.3 ready to catch errors
0 of 60842 (0%) assets queued
1000 of 60842 (2%) assets queued
2000 of 60842 (3%) assets …
```
> Obtain asset IDs for govuk_assets:store_values_generated_from_file_metadata Rake task in single fast-running query

- app/models/asset.rb
- app/models/whitehall_asset.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/models/asset_spec.rb
- spec/models/whitehall_asset_spec.rb
- spec/workers/asset_file_metadata_worker_spec.rb
This was prompted by the concern I mentioned in [this comment][1]:
> If the attributes on an `Asset` which are derived from the file metadata are set in the database and then the `Asset` is updated with a new file, the attributes will not be updated as you might expect.
In doing this work, I also realised that although the attribute values derived from file metadata were being set, they were not being persisted! This was because I had used an `after_create` callback vs `before_create` and it is fixed in the first commit (with title "Save asset attribute values generated from file metadata").
In some ways, the fact that no values were being persisted makes things simpler for us in deciding whether to merge this PR, because we know that no assets will have `etag`, `last_modified` or …
> Fix asset attributes generated from file metadata

- README.md
- app/controllers/media_controller.rb
- config/application.rb
- config/initializers/features.rb
- lib/s3_storage.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage_spec.rb
We added this functionality in #112 when we were investigating the performance of various approaches. Since we're not planning to use this behaviour in the near future and I'm not confident that the behaviour is as well tested as the other two alternatives (e.g. response headers), I think it's better to remove the functionality for now - we can always find this code in the git history if we need it again.
Note that I've retained `AssetManager.aws_s3_use_virtual_host`, because although it was introduced in #112, it's now being used for `S3Storage#presigned_url_for`.
Note also that I've checked that the `REDIRECT_ALL_ASSET_REQUESTS_TO_S3` environment variable isn't beeing set anywhere in `govuk-puppet`.
> Remove ability to redirect asset requests to S3

- app/models/asset.rb
- spec/support/matchers/be_within_a_millisecond_of.rb
- spec/workers/asset_file_metadata_worker_spec.rb
On Jenkins CI builds (but not local MacOS or development VM builds), the example for `Asser#last_modified` was slightly brittle for a couple of reasons:
* The memo-izing of `Asset#file_stat` seemed to cause odd results.
* The rounding to an integer occasionally went the wrong way.
I'm not 100% I understand what was going on, but I'm pretty confident that this fixes the problem!
> Fix brittle AssetFileMetadataWorker spec

- README.md
- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- config/application.rb
- config/initializers/features.rb
- spec/controllers/base_media_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
We're already proxying 100% of Mainstream asset requests to S3 in production (although 0% in other environments).
These changes give us the flexibility to gradually ramp up proxying Whitehall asset requests to S3 independent of the percentage set for Mainstream asset requests.
I did contemplate encapsulating the differences in Mainstream vs Whitehall asset configuration somewhere, but given that we're hoping this is only going to be a temporary change, it didn't seem worthwhile.
Closes #259.
> Independent control of proxying Whitehall vs Mainstream assets to S3

- app/controllers/whitehall_assets_controller.rb
- app/models/whitehall_asset.rb
- config/routes.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/models/whitehall_asset_spec.rb
- spec/requests/whitehall_asset_requests_spec.rb
This endpoint allows us to find a Whitehall asset using its `legacy_url_path`. We're going to use this in Whitehall to update/delete assets stored in Asset Manager.
> Add Whitehall asset endpoint

- app/models/asset.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
Now that the `govuk_assets:store_values_generated_from_file_metadata` Rake task has been run in all environments, we can rely on the presence of the value in the database which is set in a `before_save` callback by `Asset#store_metadata`.
I did consider adding validation for the presence of these attributes, but it turned out to be very awkward and in any case, I soon realised that it's a bit odd to validate attributes which are set automatically by a `before_save` callback, especially given that the attribute writer methods are protected. So I decided that adding such validation was unnecessary.
> Simplify Asset attributes obtained from file metadata

- spec/models/asset_spec.rb
This makes some of the examples in Asset spec a bit more idiomatic from an RSpec and FactoryGirl point of view. My motivation for making the changes was that I was planning to make some changes to Asset validation. I didn't end up making those changes, but I think these improvements are still worth making.
> Improvements to Asset spec

- .gitignore
- .rubocop_todo.yml
- app/controllers/application_controller.rb
- app/uploaders/asset_uploader.rb
- config/application.rb
- config/initializers/carrier_wave.rb
- config/initializers/fake_s3.rb
- config/initializers/govuk.rb
- config/routes.rb
- lib/cloud_storage.rb
- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- lib/s3_storage/null.rb
- spec/lib/s3_storage/fake_spec.rb
- spec/lib/s3_storage/null_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/routing/fake_s3_route_spec.rb
- spec/support/carrier_wave.rb
This introduces a new `S3Storage::Fake` class and configures the app to use an instance of this class in development environments if S3 is not configured.
We want to remove support for serving asset requests from NFS and proxy all of them to S3. However, having to set up the necessary S3 resources in a development environment seems rather onerous. The changes in this PR mean that by default development environments will use a *fake* version of `S3Storage` which stores the files in the local filesystem and serves them via a `Rack::File` instance mounted in the Rails app.
I did consider a couple of other options:
* The [fake-s3][3] gem allows you to run a separate server process which acts like S3 but is backed by the local file system. I chose not to use it for two reasons: (a) although …
> Fake S3 in development environments

- lib/s3_storage.rb
- spec/lib/s3_storage_spec.rb
Previously calling `S3Object#save` for an existing asset with existing metadata would overwrite the metadata with just the default "md5-hexdigest" key and value - thus any existing metadata would be lost. Now existing metadata is preserved, unless explicitly overwritten.
I've also removed the `options` argument for `S3Storage#save` - we no longer use it and it would've complicated the implementation considerably.
I've also taken the opportunity to reduce the length of a bunch of lines in `S3Storage` and its spec to make the code more readable.
> Update vs overwrite S3 object metadata

- .rubocop_todo.yml
- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- lib/s3_storage/null.rb
- spec/lib/s3_storage/fake_spec.rb
- spec/lib/s3_storage_spec.rb
These are some tidying-up commits from #286 which I still think are generally useful. Also I'm going to need the `S3Storage#exists?` method which this PR introduces when I implement the new version of #286.
> Improve consistency of methods in the S3Storage class

- app/workers/asset_trigger_replication_worker.rb
- lib/asset_processor.rb
- lib/asset_replication_checker.rb
- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- lib/s3_storage/null.rb
- lib/tasks/govuk_assets.rake
- spec/lib/s3_storage/fake_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/workers/asset_trigger_replication_worker_spec.rb
S3 objects for some assets were added to the production S3 bucket *before* replication was enabled on the bucket. Enabling replication did not automatically replicate these S3 objects, so we need to do it manually.
The simplest way to do this appears to be to re-save the S3 object. This feels better than manually syncing/copying the relevant S3 objects to the target bucket, because it uses the same mechanism (replication) to sync to the backup bucket with all the same users, roles & permissions.
One possible downside of this approach is that the `Last-Modified` timestamp updated when the metadata on an S3 object is modified. However, at the moment, we're not making use of this metadata - the Rails app sets the `Last-Modified` response header using a value stored in the database.
This PR …
> Trigger replication for non-replicated S3 objects

- lib/asset_replication_checker.rb
We tried running the `rake
govuk_assets:check_all_assets_have_been_replicated` task in production
but it failed with `NameError: uninitialized constant
AssetReplicationChecker::Services`.
> Add missing require statement to AssetReplicationChecker

- app/controllers/whitehall_media_controller.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
We redirect to this placeholder in response to requests for unscanned
Whitehall images.
We were incorrectly redirecting to '/images/thumbnail-placeholder.png'
instead of '/asset-manager/thumbnail-placeholder-<digest>.png'. This
appears to be because the `image_path` method from
`ActionView::Helpers::AssetUrlHelper` doesn't take the Asset Pipeline
into account. The code snippets below illustrate the problem and fix:
>> Class.new do
include ActionView::Helpers::AssetUrlHelper
end.new.image_path('thumbnail-placeholder.png')
=> "/images/thumbnail-placeholder.png"
>> ActionController::Base.helpers.image_path('thumbnail-placeholder.png')
=> "/asset-manager/thumbnail-placeholder-b0b645c0f44c2fc7d8cc2fee24f576d82256a85ac3c3e0a59d6ff60d2903d6b6.png"
I've confirmed that redirecting to the thumbnail …
> Generate correct path to thumbnail-placeholder.png

- app/workers/asset_trigger_replication_worker.rb
- app/workers/deleted_asset_file_metadata_worker.rb
- app/workers/deleted_asset_save_to_cloud_storage_worker.rb
- app/workers/save_to_cloud_storage_worker.rb
- lib/asset_processor.rb
- lib/tasks/govuk_assets.rake
- spec/lib/asset_processor_spec.rb
- spec/workers/asset_trigger_replication_worker_spec.rb
- spec/workers/deleted_asset_file_metadata_worker_spec.rb
- spec/workers/deleted_asset_save_to_cloud_storage_worker_spec.rb
- spec/workers/save_to_cloud_storage_worker_spec.rb
This introduces a couple of new Rake tasks:
* `upload_assets_marked_as_deleted_to_cloud_storage`
* `store_values_generated_from_file_metadata_for_assets_marked_as_deleted`
Both these Rake tasks operate on assets marked as deleted and for each of these assets the first one uploads the file to S3 and the second one store values generated from file metadata in the database.
Both Rake tasks queue jobs up in a low priority queue in the same way as we've done previously.
I've also taken the opportunity to add test coverage for the `AssetProcessor` and in the process improved its progress reporting. I've also done a bit of tidying up of the workers and their specs.
Closes #304.
> Upload assets marked as deleted to s3

- Dockerfile
The ruby version was upgraded in a recent PR #313 without bumping the Dockerfile to match.
Dockerfile gets used by the publishing end-to-end tests.  We don't want the version tested against to be different to the version in production.
CC @danielburnley @RoryMacDonald
> Match the Dockerfile ruby version to the .ruby-version

- Jenkinsfile
For: https://trello.com/c/QtpGwa2A/288-improve-feedback-on-github-for-changes-to-govuk-content-schemas
In CI we want to run asset compilation in production mode to catch any
errors before we deploy as there are differences between dev/test mode
compilation and production mode (see: https://github.com/alphagov/govuk-puppet/pull/6821).  This app requires that
AWS_S3_BUCKET_NAME is set in production, so we set that envvar in the
Jenkinsfile after we've run the tests (asset compilation is done after
the other tests).
> Set AWS_S3_BUCKET_NAME to a placeholder on CI

- app/workers/virus_scan_worker.rb
- spec/controllers/assets_controller_spec.rb
The former is [an alias of the latter][1] and we were using a mixture of the two. The former is terser and just as meaningful and so I've elected to standardize on that.
[1]:
https://github.com/carrierwaveuploader/carrierwave/blob/v0.10.0/lib/carrierwave/uploader/proxy.rb#L25
> Standardize on CarrierWave::Uploader::Proxy#path vs #current_path

- Gemfile
- Gemfile.lock
- spec/controllers/assets_controller_spec.rb
- spec/controllers/base_media_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/factories/factories.rb
- spec/lib/content_disposition_configuration_spec.rb
- spec/lib/s3_storage/fake_spec.rb
- spec/lib/s3_storage/null_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
- spec/models/whitehall_asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
- spec/requests/asset_requests_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/whitehall_asset_requests_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
- spec/support/authentication.rb
- spec/workers/save_to_cloud_storage_worker_spec.rb
- spec/workers/virus_scan_worker_spec.rb
And from `factory_girl_rails` to `factory_bot_rails`.
I followed the instructions in the following deprecation warning:
The factory_girl gem is deprecated. Please upgrade to factory_bot. See
https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md
for further instructions.
Note that the latest version of the new gems seems to be v4.8.2 which is why you will see them both "downgraded" from v4.9.0 to v4.8.2 in the `Gemfile.lock`.
> Convert from factory_girl to factory_bot gem

- .rubocop_todo.yml
- config/initializers/govuk.rb
- lib/govuk_configuration.rb
- spec/lib/govuk_configuration_spec.rb
I want to be able to set the app host to "http://localhost" or "http://127.0.0.1" for the [publishing-e2e-tests project](https://github.com/alphagov/publishing-e2e-tests). Previously I could bodge this by setting `GOVUK_APP_NAME` to "127" and `GOVUK_APP_DOMAIN` to "0.0.1", but making this change means we now have the flexibility to just set `GOVUK_APP_DOMAIN` to "localhost" or "127.0.0.1" to achieve the desired result.
I've extracted the logic into a class and added a spec before making the change to highlight how the logic has changed.
> Make app host configuration more flexible

- .rubocop_todo.yml
- config/application.rb
- config/initializers/fake_s3.rb
- config/initializers/govuk.rb
- config/routes.rb
- lib/fake_s3_configuration.rb
- lib/govuk_configuration.rb
- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- spec/lib/fake_s3_configuration_spec.rb
- spec/lib/govuk_configuration_spec.rb
- spec/lib/s3_storage/fake_spec.rb
Following on from #333, I realised I still couldn't do what I need to do in the `publishing-e2e-tests` project. So I've re-jigged things a bit and now it's possible to override the host used by the fake S3 "service" using the `FAKE_S3_HOST` environment variable.
I want to be able to do this in the `publishing-e2e-tests` project, because I want to set the fake S3 host to http://localhost and that isn't possible without this change.
> Allow override of fake S3 host via environment variable

- app/controllers/whitehall_assets_controller.rb
- spec/controllers/whitehall_assets_controller_spec.rb
Fixes: #229 
Currently in Whitehall images stored using the `ImageUploader` are
stored on NFS only. We want to change Whitehall to store these images
in Asset Manager.
In some circumstances an image using this Uploader (such as the image
associated with a Person[1]) can be replaced. For example
1. A new person is created with an image `foo.jpg`
2. The person is saved
3. The person is edited to have a different image with the same
filename `foo.jpg`
4. The person is saved again
In this sequence of events the new image will be available at the same
URL as the image added in step 1. The image added in step 1. will be
deleted from the file system.
In order to allow this behaviour in Asset Manager this commit modifies
`POST /whitehall_assets` to check whether an asset with the same …
> POST /whitehall_assets replaces existing asset

- README.md
- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- config/application.rb
- config/initializers/features.rb
- spec/controllers/base_media_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/virus_scanning_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
Currently both feature flags are [set to 100% in all environments][1], so *all* asset requests are being proxied to S3 via Nginx. We're happy that this mechanism is working OK and have no plans to rollback to proxying less than 100% of asset requests to S3 via Nginx, so there's no longer
any need for either the environment variable feature flags nor the request parameter overrides. This pull request hard-codes these configuration options and simplifies the application code accordingly.
My actual motivation for doing this is that I want to [start deleting asset files from NFS when they've been uploaded to S3](https://github.com/alphagov/asset-manager/issues/323). These changes should make that easier, because it removes one key method (`BaseMediaController#serve_from_nfs_via_nginx`) which …
> Remove options to serve assets from NFS via Nginx

- app/controllers/whitehall_media_controller.rb
- spec/controllers/whitehall_media_controller_spec.rb
[We were re-constructing the `legacy_url_path` to search for by assuming there was a format][1]. Thus if an asset had no file extension, e.g. `/government/uploads/foo`, we were attempting to lookup the asset using `/government/uploads/foo.` (note the trailing full-stop). This did not find the asset and the app responded with a `404 Not Found`.
[1]:
https://github.com/alphagov/asset-manager/blob/c14c324b4f41467ab6356599bc95ea92b34b99f6/app/controllers/whitehall_media_controller.rb#L3-L4
> Fix Whitehall asset lookup when URL path has no format/file extension

- README.md
- config/application.rb
- config/initializers/aws.rb
- lib/s3_storage.rb
- spec/lib/s3_storage_spec.rb
This option was [added for experimental use in development only][1] and has never been enabled in any other environments. Although eventually we might end up wanting to use this functionality, at the moment it's just making the code more complicated for no good reason.
[1]: https://github.com/alphagov/asset-manager/commit/552e396ae5200c38852674b7dafcdc65467b5cb5
> Remove unused S3 virtual host option

- app/controllers/base_media_controller.rb
- spec/controllers/base_media_controller_spec.rb
This should avoid the problem captured in issue #238 ("Binary file content being displaying in Internet Explorer").
We believe that the problem was being triggered when Fastly made a conditional GET request for an asset that it had stored in its cache. Rails (or more specifically, [`Rack::ConditionalGet`][1]) would respond with a 304 Not Modified and an empty `Content-Type` and empty `Content-Length` header. This would've been fine if it didn't also send the `X-Accel-Redirect` header. The presence of this header was telling Nginx to request the file from S3 again. Nginx would then send a 200 response containing the asset but with an empty `Content-Type` header!
By not sending the `X-Accel-Redirect` header along with a 304 response, we ensure that Nginx passes the 304 back to Fastly as …
> Prevent nginx unnecessarily downloading assets from S3

- .rubocop.yml
- .rubocop_todo.yml
I was triggering violations of this cop quite regularly. I think the default value of 2 is a bit draconian and rather than continuing to add files to the exclusion list, I think it's more sensible to bump up the value to 4.
Meanwhile I've opened [an issue][1] to suggest this should become the default for govuk-lint.
[1]: https://github.com/alphagov/govuk-lint/issues/91
> Increase Max option for RSpec/NestedGroups cop from 2 -> 4

- .rubocop_todo.yml
- lib/s3_configuration.rb
- spec/lib/s3_configuration_spec.rb
The motivation behind this is two-fold:
1. I want to be able to use the fake S3 functionality in the Rails test environment in order to write some integration testing which involve uploading to S3.
2. The team working on the publishing-e2e-tests project want to be able to use the fake S3 functionality in the tests when running the app in the Rails production environment.
The idea is to make the methods on `S3Configuration` as self-explanatory as possible and to make it hard to enable the fake S3 functionality in production by accident.
I've intentionally not added the new environment variable, `ALLOW_FAKE_S3_IN_PRODUCTION_FOR_PUBLISHING_E2E_TESTS` to the documentation, because I don't want to encourage its use and in any case, its name makes its purpose pretty clear.
This supersedes #338.
> Allow use of fake S3 in non-development environments

- config/application.rb
Since alphagov/asset-manager#328 the Rails app only ever proxies asset requests to S3; it no longer instructs Nginx to serve asset files from NFS. And so this setting is no longer needed. It seems as if it is this setting which is causing `Rack::Sendfile` to emit the warning mentioned above.
We're planning to remove the redundant `Sendfile`-related config from the asset-manager Nginx virtual host in alphagov/govuk-puppet#6971, but this change doesn't need to wait until that is deployed/applied.
Note that The x_sendfile_header configuration option was originally set to `X-Sendfile` in [this commit][1] and then to `X-Accel-Redirect` in [this commit][2].
[1]: https://github.com/alphagov/asset-manager/commit/9be379ed8a8f5622a67151884325d21d52c8f3a3
[2]: …
> Avoid "X-Accel-Mapping header missing" warning

- app/controllers/media_controller.rb
- app/models/asset.rb
- app/workers/asset_upload_state_worker.rb
- app/workers/save_to_cloud_storage_worker.rb
- lib/asset_processor.rb
- lib/s3_storage.rb
- lib/tasks/govuk_assets.rake
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/factories/factories.rb
- spec/lib/asset_processor_spec.rb
- spec/lib/s3_storage_spec.rb
- spec/models/asset_spec.rb
- spec/requests/virus_scanning_spec.rb
- spec/routing/fake_s3_route_spec.rb
- spec/workers/asset_upload_state_worker_spec.rb
- spec/workers/save_to_cloud_storage_worker_spec.rb
This supersedes #363.
This introduces a new "uploaded" asset state. New assets are still scanned for viruses and if no viruses are found they are marked as "clean". However, now they will be marked as "uploaded" or if the subsequent upload to cloud storage is successful.
For the moment, assets in the "clean" and "uploaded" states are treated the same. I've made use of shared examples in the two media controller specs to check this without introducing duplication. However, once the `govuk:update_state_for_clean_assets_with_s3_object_to_uploaded` Rake task included in this PR has been run, we'll be in a position to treat these states differently and at that point we should be able to do away with the shared examples.
The motivation behind this PR is two-fold:
1. Now that all asset requests …
> Introduce "uploaded" state for assets

- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/factories/factories.rb
- spec/requests/asset_requests_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/virus_scanning_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
Previously requests for Whitehall assets which had been virus scanned, but not uploaded to S3, resulted in a `200 OK` response with a `X-Accel-Redirect` header set to a URL for an S3 object which did not exist. The Nginx internal redirect then requested the S3 URL which resulted in a `404 Not Found`. This was at odds with the response for an unscanned asset which is a redirect to a placeholder image/page. This PR changes the behaviour for an asset which has been virus scanned, but not uploaded to S3, to be the same as for an asset which has not yet been virus scanned, i.e. the app will response with a redirect to the placeholder image/page.
The same issue existed for Mainstream assets, but the consequences were less obvious/serious. Requests for such assets which had been virus scanned, …
> Only attempt to serve asset if successfully uploaded to S3

- app/workers/virus_scan_worker.rb
- lib/services.rb
- lib/virus_scanner.rb
- spec/lib/virus_scanner_spec.rb
- spec/workers/virus_scan_worker_spec.rb
I think this simplifies the code, makes it easier to test and bring this app more into line with other GOV.UK apps.
> Convert VirusScanner class into stateless service

- bin/create_asset
- bin/update_asset
- lib/cli.rb
- spec/lib/cli_spec.rb
I've extracted the two custom scripts (`bin/create_asset` & `bin/update_asset`) into methods on a new class (`CLI`) and added a spec for that class.
In doing this I identified a slight flaw in the argument parsing of `bin/update_asset` which I have fixed. Other than that I've attempted to keep the code as unchanged as possible, albeit with some changes to make testing easier. This is not because I think the code is especially good, but because I wanted to minimise the chance of introducing bugs.
I did contemplate turning them into Rake tasks as we did in Manuals Publisher, but I realised that would mean updating [the corresponding documentation](https://github.com/alphagov/govuk-developer-docs/blob/8757e2bcc61469b8d94f3d09a552c1608b17a90c/source/manual/howto-upload-an-asset-to-asset-manage …
> Add test coverage for scripts

- app/models/asset.rb
- app/workers/delete_asset_file_from_nfs_worker.rb
- lib/asset_processor.rb
- lib/tasks/govuk_assets.rake
- spec/lib/asset_processor_spec.rb
- spec/models/asset_spec.rb
- spec/workers/delete_asset_file_from_nfs_worker_spec.rb
Since #328 the app hasn't been capable of instructing Nginx to serve assets directly from the NFS mount and since alphagov/govuk-puppet#6971 Nginx hasn't been configured to allow assets to be served directly from the NFS mount.
This means that the only reason we need to store files on NFS is currently so that the Sidekiq workers (which may be running on different machines to that which handled the upload request) have access to the files.
This in turn means that it is safe to remove the underlying file once the asset has been scanned for viruses and uploaded to S3.
In order to achieve this I've introduced a new state transition callback which calls `Asset#remove_file!`. The latter seems to be the recommended way to remove the underlying file via the Carrierwave API and results in …
> Delete underlying file when upload to S3 succeeds

- app/models/asset.rb
- spec/models/asset_spec.rb
- spec/support/carrier_wave.rb
Since #373 we've been deleting an asset's underlying file from the filesystem once the file has been uploaded to S3. However, this was leaving behind a bunch of empty directories. This change means that the app now removes all empty parent directories when the file is removed.
The immediate motivation behind this change is that once alphagov/govuk-puppet#7016 is applied in production, the Asset Manager CarrierWave directory will no longer be sync-ed from the Asset Master to the Asset Slaves and there will therefore be a danger that the [`asset_master_and_slave_disk_space_similar_from_xxx` Icinga alert][1] might eventually be triggered by the non-zero disk space taken up by the empty directories.
The implementation makes use of `FileUtils.rmdir` with the `parents` option which is …
> Remove empty CarrierWave directories when new asset is created and file is removed after upload to S3

- Dockerfile
The existing healthcheck errors out as there is nothing available on the
root route. This resolves that issue by using the provided healthcheck
route.
> Update Docker Healthcheck to use healthcheck route

- Gemfile
- Gemfile.lock
- app/presenters/asset_presenter.rb
- spec/presenters/asset_presenter_spec.rb
This supersedes PR #393.
We've found a number of Whitehall assets whose filenames (and therefore
their `legacy_url_path`s) contain non-ascii characters. We can safely
store these non-ascii characters in the database but need to escape them
when constructing the `file_url` in the JSON representation of an asset.
This addresses the bug described in issue #395.
I initially used Ruby's `URI.escape` method but Rubocop doesn't like
that as it's been marked as obsolete.
After this change we can upload and request a Whitehall asset whose
legacy_url_path contains a non-ascii character:
```
$ echo `date` > whitehall-assét.txt
$ curl http://asset-manager.dev.gov.uk/whitehall_assets \
--form "asset[file]=@whitehall-assét.txt" \
--form "asset[legacy_url_path]=/government/uploads/path/to/whitehall-assét …
```
> Percent encode public_url_path in asset JSON

- app/models/asset.rb
- spec/models/asset_spec.rb
- spec/support/carrier_wave.rb
This reverts commit 53fe16b04a24a4244f7cc03e07a0da34110d6028, reversing changes made to 1cb2caed8d0c340d2908865e1b30dbf8ee2fecdc.
I'm reverting #390, because we've been seeing the following exceptions:
* [`VirusScanner::Error` in `Sidekiq/VirusScanWorker`][1]
* [`Errno::ENOENT` in `Sidekiq/SaveToCloudStorageWorker`][2]
Which both look as if they are likely to be related to the removal of directories supposedly after a file has been uploaded to S3.
[1]: https://sentry.io/govuk/app-asset-manager/issues/432945964/
[2]: https://sentry.io/govuk/app-asset-manager/issues/433068645/
> Revert "Remove empty CarrierWave directories when new asset is created and file is removed after upload to S3" (#390)

- app/models/whitehall_asset.rb
We've seen a marked slow-down in creating Whitehall assets since a large number of them have been migrated from Whitehall to Asset Manager and we think this slow-down may be causing [`GdsApi::TimedOutException` exceptions][1] in Whitehall.
The following controller actions lookup Whitehall assets using `legacy_url_path`:
* WhitehallAssetsController#create
* WhitehallAssetsController#show
* WhitehallMediacontroller#download
In adding this index, I can see that the `totalDocsExamined` number in the explanation of the query comes down from 65660 (the total number of assets) to 1 on my local machine. I believe there are now more than 600K assets in Asset Manager in production and so the speed up should be considerable.
My only hesitation is how long it will take to apply the index in …
> Add MongoDB index for Asset#legacy_url_path

- app/controllers/healthcheck_controller.rb
- app/models/healthcheck.rb
- app/models/healthcheck/database_healthcheck.rb
- app/models/healthcheck/redis_healthcheck.rb
- config/routes.rb
- spec/models/healthcheck/database_healthcheck_spec.rb
- spec/models/healthcheck/redis_healthcheck_spec.rb
- spec/models/healthcheck_spec.rb
- spec/requests/healthcheck_spec.rb
This was motivated by the recent discovery that Asset Manager wasn't properly configured to connect to Redis in the new AWS integration environment. If this healthcheck had been present, we would've been alerted to the problem much sooner.
This is modelled closely on the code in the [email-alert-api repo][1]. For now I've only included checks for mongo & redis connectivity. We can always add further checks later.
* I've included the logic for warnings as well as critical errors even though the checks I've included only report critical errors.
* I've included the logic for reporting details of the warnings/errors even though the checks I've included don't report any details.
* I had to make some changes to the code to fix some Rubocop RSpec violations, e.g. introduce a base class …
> Include mongo & redis checks in healthcheck action

- config/initializers/mime_types.rb
- spec/models/asset_spec.rb
This addresses https://github.com/alphagov/asset-manager/issues/417 and https://github.com/alphagov/asset-manager/issues/408.
I've ensured we're setting the correct `Content-Type` header for assets allowed by Whitehall's non-attachments assets that we're in the process of migrating to Asset Manager.
> Ensure we support content types of whitehall assets

- app/controllers/media_controller.rb
- app/models/asset.rb
- lib/tasks/db.rake
- spec/controllers/media_controller_spec.rb
- spec/factories/factories.rb
- spec/models/asset_spec.rb
We're about to add functionality to the Asset Manager to protect draft assets behind SSO and this unused functionality just confuses matters. Note that this PR probably also addresses the concerns detailed in https://github.com/alphagov/asset-manager/issues/156.
Although in govuk-puppet [the `PRIVATE_ASSET_MANAGER_HOST` environment variable is set to `private-asset-manager.${app_domain}`][1] and [`private-asset-manager` is added as an alias to the `asset-manager` virtual host][2], the Asset Manager app never supplies URLs using this hostname to publishing apps and I haven't found any evidence that any of the publishing apps manually construct URLs using this hostname. So as far as I can tell this functionality is not currently (and possibly has never been) used.
We're about to add …
> Remove unused access-limiting functionality

- app/controllers/assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/models/asset.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/models/asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
We want to migrate Whitehall attachments to Asset Manager, but Whitehall currently protects draft attachments behind SSO, so before we can do the migration we need to implement similar functionality in Asset Manager. This PR is the first small step towards doing that - it makes it possible to mark an asset as draft when calling the "create" & "update" API actions. It includes the draft status of an asset in the response to those API calls and the "show" API call.
See #431.
* For the moment, public requests for assets marked as draft are treated the same as those for assets not marked as draft. I plan to introduce authentication, etc, as a separate PR when addressing #432.
* I've consciously chosen not to update the documentation for the moment since this is somewhat experimental …
> Allow assets to be marked as draft

- README.md
The API is made available on a different domain in the new AWS version of the integration environment. This updates the usage examples to take this into account and makes some other improvements including making use of `govuk_setenv` to make use of environment variables already available on the relevant machines and to make the examples more portable.
Note that I haven't bothered updating the command line prompts to realistic values, because they are much more verbose in the AWS environment and I don't think the realistic values impart much more useful info.
> Update example usage of API in integration environment

- Gemfile.lock
- app/controllers/base_media_controller.rb
- config/application.rb
- config/initializers/govuk.rb
- lib/govuk_configuration.rb
- spec/controllers/base_media_controller_spec.rb
- spec/lib/govuk_configuration_spec.rb
The main change in this PR is in the last commit which means that any request from the `draft-assets` host requires SSO authentication.
In a future PR we plan to redirect requests from the
`assets-origin` host for assets marked as draft to the `draft-assets` host.
Note that this change applies to both Mainstream & Whitehall assets.
Note also that we're using the new `Plek#external_url_for` method to obtain the external version of the `draft-assets` host which should mean the functionality works in AWS environments (currently only integration).
Supersedes #432.
> Require authentication for requests from draft-assets host

- config/application.rb
This was made redundant in [this commit][1] and should have been removed at that point.
[1]:https://github.com/alphagov/asset-manager/commit/e6f630f0e335b0a1bb6db9366a6bd8c4da31a943
> Remove unused AssetManager.app_host accessor

- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
The significant changes are in the final commit of this PR which redirects requests for assets marked as draft to the `draft-assets` host if they have come from another host, typically `assets-origin`.
Assets marked as draft should only be accessed via the draft-assets host which requires authentication as of #444.
Note that these changes apply to both Mainstream & Whitehall assets.
Although I've managed to extract the common functionality into `BaseMediaController#redirected_to_draft_assets_host_for?`, I've ended up adding examples to the specs for both `MediaController` & `WhitehallMediaController`, because I found it awkward to add them to `BaseMediaController` spec.
I'm not entirely happy with the resulting code, but it's the best compromise I could come up with. Hopefully as we bring …
> Redirect requests for assets marked as draft to draft-assets host

- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
The previous implementation was non-standard and therefore confusing. In particular, the
`BaseMediaController#redirected_to_draft_assets_host_for?` method looked like a query method, but was actually a command method, i.e. it had side effects which might have been surprising. By splitting this method into a query method and a command method, we can avoid this confusion at the expense of a little duplication.
Addresses [this comment in an earlier PR](https://github.com/alphagov/asset-manager/pull/446#pullrequestreview-92674337).
> Standardize code for redirecting to draft-assets host

- app/controllers/assets_controller.rb
- app/controllers/base_assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/whitehall_asset.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/models/whitehall_asset_spec.rb
I started work on this, because I wanted to add an `update` action to the `WhitehallAssetsController`, but I was painfully aware that we already had a bunch of duplication. However, having chatted to @chrisroos I've now convinced myself that we don't need this `update` action - we can just use a combination of `WhitehallAssetsController#show` & `AssetsController#update`.
I think some or all of the following work is still useful, because I fixed a couple of things and removed a bunch of duplication. However, I'm happy if people think it's not useful.
The fixes are in these commits:
* "Fix asset lookup in WhitehallAssetsController#show with no format"
* "Remove duplicate examples from AssetsController spec"
* "Move context into describe block in AssetsController spec"
The other commits are …
> Refactor assets controllers

- app/controllers/base_assets_controller.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
This changes the `AssetsController#show` and `WhitehallAssetsController#show` endpoints so that the `Cache-Control` header is always set to have `max-age=0`, i.e. indicating that the response should not be cached.
This logic became out-of-date when we introduced the uploaded state in [this PR][1]. I considered only updating the logic to fix this, i.e. by setting cache expiry to 0 for 'uploaded' or 'infected' assets (vs 'scanned' or 'infected' assets).
However, I realised that since we introduced the `draft` status of an asset in [this PR][2] and included it in the JSON response, it no longer makes sense to set the cache expiry to 0 for uploaded assets, because their `draft` status may change, even after they have been virus scanned and uploaded cloud storage.
Since very few assets are …
> Prevent caching of API endpoint for getting asset details

- app/models/asset.rb
- app/workers/save_to_cloud_storage_worker.rb
- app/workers/virus_scan_worker.rb
- spec/models/asset_spec.rb
- spec/workers/save_to_cloud_storage_worker_spec.rb
- spec/workers/virus_scan_worker_spec.rb
The main purpose of this PR is to make the `SaveToCloudStorageWorker` & `VirusScanWorker` jobs idempotent. These are the only two jobs used in standard operation, the only other one, `DeleteAssetFileFromNfsWorker`, has served its purpose and will soon be removed.
My motivation for making this change is that on a couple of occasions I've seen these jobs apparently fail, because the underlying file no longer exists. And on at least one occasion the state of the asset has still been changed to 'uploaded' and the asset appears to have been saved to the cloud. This suggests that the job may have executed more than once. If that is indeed what happened, these changes should avoid that happening again.
Also [the Sidekiq documentation recommends ensuring jobs are idempotent][1].
As part of this …
> Improvements to Sidekiq workers

- lib/govuk_configuration.rb
- lib/virus_scanner.rb
- spec/lib/govuk_configuration_spec.rb
- spec/lib/virus_scanner_spec.rb
In the end to end tests environment, we want to be able to disable the virus scan easily as it can take more than 60 seconds to complete a scan when several requests are made to it at once.
By allowing the path to be passed in we can give it /bin/true when wanting to disable the scan.
> Allow location of clamscan to be configured by environment variable

- config/initializers/gds-sso.rb
The default is not to cache, and this means that large numbers of
requests are being made to Signon. Hopefully caching will reduce this.
> Configure GDS::SSO caching

- app/controllers/assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/asset.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/presenters/asset_presenter_spec.rb
The plan is for Whitehall to set `Asset#redirect_url` for an attachment if its parent document is unpublished. This relates to the logic in [Whitehall's `AttachmentController#fail`](https://github.com/alphagov/whitehall/blob/64bb168edf383fc62a7190f614f6822df9dff4a7/app/controllers/attachments_controller.rb#L43-L44) which determines whether the attachment's parent document has been unpublished.
This PR makes it possible to set a `redirect_url` attribute on any asset via the `update` API endpotin and to see its value via the `show` API endpoint. It also does the redirect if the attribute is set, but only for Whitehall assets.
In Asset Manager the concept of a "draft" asset means that requests for it must come via the `draft-assets` host and be associated with an authenticated user. Thus to …
> Add redirect_url to assets & redirect requests for Whitehall assets with redirect_url

- app/models/asset.rb
- app/presenters/asset_presenter.rb
- lib/tasks/db.rake
- spec/factories/factories.rb
- spec/models/asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
See: https://github.com/alphagov/asset-manager/issues/482
This PR adds an integer `size` attribtute to the JSON returned from a call to `GET http://asset-manager.<host>/assets/<id>`.  The JSON returned now looks like
```
{
"_response_info": {
"status": "ok"
},
"id": "http://asset-manager.dev.gov.uk/assets/5a689582759b744e3518efd8",
"name": "minister-of-funk.960x640.jpg",
"content_type": "image/jpeg",
"size": 108106,
"file_url": "http://assets-origin.dev.gov.uk/government/uploads/system/uploads/image_data/file/41/minister-of-funk.960x640.jpg",
"state": "uploaded",
"draft": false
}
```
The first 3 commits add the methods required to save the size to the database from the result of `stat`ing the file on disk before it is uploaded. These methods are very similar to the ones for setting …
> Add asset file size to API

- app/models/asset.rb
- app/workers/set_asset_size_worker.rb
- lib/tasks/db.rake
- spec/models/asset_spec.rb
- spec/workers/set_asset_size_worker_spec.rb
In 16e323e we added a rake task to set the `size` field for all
existing assets. When we ran the task in integration however, we
estimated that it would take around 12 hours to complete. This runs
the risk of the rake task being killed and leaving the database in a
somewhat inconsistent state.
This PR moves the work of the rake task into a worker. Hopefully
this will improve the run time as the workers run with concurrency,
and the rake task that queues up the jobs will complete more quickly.
> Use worker for asset size migration

- Dockerfile
- Procfile
Wider context: https://github.com/alphagov/publishing-e2e-tests/pull/202
This PR adds foreman as a gem dependency of docker (as per [foreman instructions](https://github.com/ddollar/foreman#installation)) as the means to run the processes for this app.
It also adds the web process to the Profile to boot the web server.
> Run e2e tests via foreman

- app/controllers/assets_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/asset.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/requests/access_limited_assets_spec.rb
- spec/requests/access_limited_whitehall_assets_spec.rb
Certain documents in Whitehall can be marked as access limited; which means that they're only accessible to users within the same organisation(s) that the document belongs to. Any attachments belonging to those documents should be subject to the same restrictions. This branch adds functionality to allow access to draft assets to be restricted to a subset of users. Setting the `access_limited` attribute to an array of users' UIDs will allow _only_ those users to access the asset when its in draft.
This implementation is based on a cut-down version of the equivalent functionality in the Content Store; notably I'm not storing the `auth_bypass_ids` that it's possible to set on a `ContentItem` in the Content Store.
Note the additional duplication in the two media controllers. I imagine we'll …
> Allow draft asset access to be restricted to specific users

- Gemfile
- Gemfile.lock
This was originally added in the [upgrade of Rails from v3.2.22 to v4.2.4][1] as one of the [standard gems][2]. It should have been removed in the [upgrade of Rails from v4.2.10 to v5.1.4][3] in which it was removed from the [standard set of gems][4].
The Rake task mentioned in the comment no longer works and as far as I can see we've never made use of it.
This PR makes 476 redundant.
[1]:
https://github.com/alphagov/asset-manager/commit/993e89469cddfa347b734cfa65503d0ca7c4562e
[2]: http://railsdiff.org/3.2.22/4.2.4
[3]:
https://github.com/alphagov/asset-manager/commit/ea6dc082ee9940c1e10bb695de7353ff3ca661f1
[4]: http://railsdiff.org/4.2.10/5.1.4
> Remove unused sdoc gem

- Gemfile
- Gemfile.lock
I loosened the constraint on the aws-sdk gem in the Gemfile to allow any 2.x version and then ran the following command:
bundle update --conservative aws-sdk
This has upgraded to the latest 2.x version. I've looked through [the changelog][1] and it looks as if all the changes are new features, so this should be a safe upgrade, although it would be sensible to test the app in integration, i.e. with a real S3 connection.
As per the review on [this PR][2], I don't want to upgrade to v3.x, because it includes breaking changes.
I plan to close #478 in favour of this PR.
[1]: https://github.com/aws/aws-sdk-ruby/blob/version-2/CHANGELOG.md
[2]: https://github.com/alphagov/asset-manager/pull/352
> Upgrade aws-sdk from v2.10.105 -> v2.11.3, i.e. latest 2.x

- config/initializers/mime_types.rb
- spec/models/asset_spec.rb
See: https://github.com/alphagov/asset-manager/issues/419
We are planning to change nginx so that requests for Whitehall attachments are served from Asset Manager instead of Whitehall. We've looked at all the existing attachments under `attachment_data` and requested examples of them to see what Content-Type header they are served with (#419). This PR registers the missing types so that the assets are served with the correct header.
> Add Whitehall Attachment Content-Type headers

- app/controllers/assets_controller.rb
- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/asset.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
When a Whitehall attachment is "replaced", requests for its URL result in a redirect to the attachment which replaced it. This PR implements this functionality in Asset Manager so that we'll be able to serve Whitehall attachments from Asset Manager without changing the externally visible behaviour.
This PR introduces the `Asset#replacement` association. If an asset has such a replacement then requests for it are redirected to the path for the replacement. This is equivalent to [the behaviour implemented in Whitehall's `AttachmentsController#fail` method][1].
This PR also allows a `replacement_id` to be specified when creating or updating an asset via the API. I plan to call this [when an attachment is replaced in Whitehall][2].
Notes:
* I have not addressed the issue of setting a …
> Allow asset to be replaced with another asset

- app/models/asset.rb
- spec/models/asset_spec.rb
This PR prevents assets being changed from published to draft if they have been replaced by another asset or have had a `redirect_url` set on them (which happens when they are associated with an unpublished/withdrawn Whitehall edition).
We probably don't ever want to make a published asset draft, because it's URL will be out in the wild. However, this is _definitely_ the case when the asset has been replaced or redirected, because we'll always want the redirect to be publicly accessible.
This commit adds validation on Asset to prevent such a draft status transition for replaced or redirected assets.
My motivation for making this change was the uncertainty I've expressed in https://github.com/alphagov/whitehall/pull/3827 about whether the logic in Whitehall might mean that it inadvertently …
> Prevent certain published assets from being marked as draft

- app/controllers/assets_controller.rb
- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/controllers/whitehall_media_controller.rb
- app/models/asset.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
Whitehall attachments can include a `Link` header containing the URL of their parent document (added to Whitehall in alphagov/whitehall#2202). We need to add support for this functionality to Asset Manager so that we can serve Whitehall attachments from this app.
Although this is primarily for Whitehall attachments I felt that it'd be less confusing to add support for it to both non-Whitehall and Whitehall assets.
> Add support for parent document URL to Asset Manager

- app/controllers/assets_controller.rb
- app/controllers/base_assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- spec/controllers/assets_controller_spec.rb
While investigating issue #450, I noticed that resetting/removing the access_limited status of an asset wasn't working as expected.
This is because when we pass an empty `access_limited` array to gds-api-adapters/rest-client it's turned into an empty string in Asset Manager. This results in an `UnpermittedParameter` exception for the `access_limited` parameter in Asset Manager as it's expecting an Array but receives a String. The fix is to detect the empty string in the controller and convert it back into the empty array that's intended. I don't think this is particularly nice but I think it's good enough for now.
Note that I haven't had to use `handle_empty_access_limited_param` in `WhitehallAssetsController#asset_params` as the problem only occurs when _updating_ an access-limited …
> Allow access_limited to be reset on update

- config/initializers/gds-sso.rb
I noticed that visiting the draft-assets host was resulting in a redirect to the internal signon URL (e.g. https://signon.integration.govuk-internal.digital). It should be redirecting to the external URL (e.g. https://signon.integration.publishing.service.gov.uk) as we need to be able to follow it in a browser.
Note that We're not yet sending any traffic to draft-assets so this incorrect behaviour wasn't actually causing us a problem.
I've [added a test to Smokey][1] to help avoid this problem in future.
[1]: https://github.com/alphagov/smokey/pull/341
> Use external signon URL for OAuth exchange

- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
Draft assets can be optionally access-limited to a subset of users.
Caching the response to a request for an access-limited draft asset
might mean that unauthorised users can see things they shouldn't be able
to.
This is similar to the behaviour in Whitehall where [attachment requests
made by signed-in users aren't cached][1].
[1]: https://github.com/alphagov/whitehall/blob/cc57fbae96042952584d90583952d077be1c59a8/app/controllers/base_attachments_controller.rb#L35
> Avoid caching responses made to draft-assets host

- lib/tasks/create_missing_whitehall_assets.rake
In issue #525 we've identified a number of Whitehall attachments that don't have a corresponding file on the filesystem. A subset of these attachments have a `replaced_by` object which results in requests for the original URL being redirected to the `replaced_by` URL. This Rake task creates assets for these attachments so that the redirects continue to work once we start serving the attachments from Asset Manager.
The scripts we used to come up with the hardcoded list of redirects are linked to from issue #525.
> Add temporary Rake task for creating Whitehall Attachments

- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
It's possible to replace a public asset with a draft asset. Normal replacement behaviour is to redirect from the old to the new asset; but we shouldn't redirect requests for the public asset in this instance as it'll mean we send the user to an asset they don't have permission to view. Note that we do redirect if the user requested the public asset from the draft-assets host as it means they're authenticated and therefore authorised (barring any additional access-limiting) to view draft assets.
This change follows a similar problem in Whitehall where we were inadvertently redirecting a subset of Attachments to a non-accessible draft version. See https://github.com/alphagov/whitehall/pull/3894 for some more information.
> Avoid redirecting to non-accessible assets

- app/models/asset.rb
- spec/models/asset_spec.rb
We saw some exceptions when updating the metadata of Whitehall attachments stored in Asset Manager. Some of these attachments had been replaced by assets that had subsequently been deleted. This left the assets in an invalid state and meant that we couldn't update them.
We considered removing the `replacement_id` foreign key when a replacement is deleted but weren't keen on losing that data. Allowing an asset to be valid if it's been replaced by a deleted asset feels slightly safer.
See https://github.com/alphagov/asset-manager/issues/533 for some more information.
> Assets should be valid if their replacement has been deleted

- app/controllers/base_assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/presenters/asset_presenter_spec.rb
- spec/requests/asset_requests_spec.rb
We're seeing a number of problems in Whitehall when it's trying to update attachments in Asset Manager. A large number of these are being caused by us not being able to retrieve information about assets that have been deleted. This change should help improve the situation.
More generally, I think this is a reasonable change to make given that there's an API restore endpoint that undeletes a previously deleted asset. I think it's probably useful to be able to query the API to determine the state of the asset before attempting to delete it.
Note that it's not possible to update a previously deleted asset, nor is it possible to request the content of a deleted asset.
> Allow deleted assets to be retrieved using the API

- app/models/whitehall_asset.rb
- spec/models/whitehall_asset_spec.rb
Currently, if the whitehall asset legacy_url_path isn't unique, it finds the first one by ID, rather than finding the most recent.
Paired with @barrucadu.
[Trello Card](https://trello.com/c/VybIxQvG/104-fix-assetmanagerupdateassetworkerassetmanagerassetdeleted-error-in-whitehall)
> Show most recent whitehall asset

- app/models/asset.rb
- lib/tasks/db.rake
- spec/models/asset_spec.rb
Say we have an asset `A`, which gets replaced with an asset `B`.  We have this situation:
```
A    ---[replaced by]--->     B
```
When users request asset `A`, they get a redirect to asset `B`.  So far so good.
But what happens then if asset `B` is replaced with asset `C`, giving us this situation: ?
```
A    ---[replaced by]--->     B    ---[replaced by]--->     C
```
When users request asset `B`, they get redirected to asset `C`.  But when users request asset `A` they first get redirected to asset `B`!  This redirect chaining is bad, we want to redirect to the final asset in the replacement chain in one step.
The simplest way to do this is to (recursively) update assets when their replacement gets replaced.  So when `B` is replaced by `C` we end up with this:
```
A    ---[replaced …
```
> Update replaced assets to avoid redirect chains

- app/controllers/base_media_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_media_controller.rb
- config/application.rb
- config/initializers/frame_options.rb
- spec/requests/media_requests_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
This breaks anything which embeds whitehall assets in an iframe,
however:
- whitehall only uses iframes for external videos
- government-frontend doesn't use iframes at all
So this more conservative header should be safe.
OWASP recommends DENY unless there is a specific reason to use
something else, which is why I didn't change everything to use
SAMEORIGIN instead.
---
Closes #249 
[Trello card](https://trello.com/c/Rx2IiQPR/156-standardise-use-of-x-frame-options-response-header-for-whitehall-vs-mainstream-assets-2)
> Set X-Frame-Options: DENY for whitehall assets

- app/models/asset.rb
There are queries on this field a lot and we noticed a query that was taking 3 seconds to run. We've already added this index in production so we should also include it in the model.
> Add index to uuid field

- app/models/asset.rb
We've found some queries are running slow without this index and we've already added the index in production.
[Trello Card](https://trello.com/c/uSPO7Sc9/185-investigate-potential-problem-with-whitehall-assets-blocking-publishing-to-the-publishing-api-3)
> Add index to replacement_id field

- app/models/asset.rb
Transitioning to a state doesn't save asset, so we think there's a problem with transitioning to the `uploaded` state:
1. Transition happens
2. `after_transition to: :uploaded` triggers, deleting the file.
3. Save happens
4. `before_save : store_metadata` triggers, raising an exception when it can't read the file.
> Save asset before removing file

- app/controllers/base_assets_controller.rb
- spec/controllers/assets_controller_spec.rb
b9e3a6a3cae336069913959a67d928bcb3889beb strips out blank redirect URLs from updates because `nil` redirect URLs manifest in the app as empty strings, in part justifying the change by pointing out that the default redirect URL is `nil`, so we never want to set it to an empty string.
However, there's a perfectly legitimate use-case for setting a non-`nil` redirect URL to `nil`: if someone unpublishes a document with an attachment, and then republishes it.  Unpublishing will set the redirect URL, but republishing will not remove the redirect URL currently because of this logic.
This PR changes the logic to normalise empty strings to `nil` redirect URLs.
---
This change is safe **if** all publishing apps which send `{ redirect_url: nil }` only do so when they actually want to unset the …
> Allow unsetting redirect URLs

- config/routes.rb
This redirects an asset currently 404s. Temporary until we figure out how to properly redirect an asset.
> Set up temporary redirect

- config/routes.rb
Reverts alphagov/asset-manager#573
We don't need this custom redirect as we will fix the attachment directly.
> Revert "Set up temporary redirect"

- app/controllers/media_controller.rb
- app/models/healthcheck/database_healthcheck.rb
- app/models/whitehall_asset.rb
- app/workers/delete_asset_file_from_nfs_worker.rb
- app/workers/save_to_cloud_storage_worker.rb
- app/workers/set_asset_size_worker.rb
- lib/tasks/db.rake
- lib/tasks/govuk_assets.rake
- spec/controllers/media_controller_spec.rb
- spec/models/healthcheck/database_healthcheck_spec.rb
- spec/models/whitehall_asset_spec.rb
https://trello.com/c/VubcGtSx/343-investigate-asset-manager-default-scopes
Missed in https://github.com/alphagov/asset-manager/pull/578
This PR tidies up redundant calls to `.unscoped` and uses the correct `.undeleted` scope where appropriate.
> Use undeleted scope and remove unscoped queries

- lib/tasks/govuk_assets.rake
HMRC PAYE files are manually uploaded, because we don't normally allow exe files on GOV.UK.  Infrequently, we will receive a zendesk ticket with a bunch of new files attached.  These files are:
* `payetools-{linux,osx,win}.zip` - the full binary
* `payetools-rti-$version-{linux,osx,win}.zip` - the binary patch updates
* `realtimepayetools-update-vXX.xml` - a manifest file describing the patch update locations and versions
There may be additional files (`payetools-rti-patch-*` and `*-win-assistive.zip` are common), but these 7 are always present, so they are what the rake task uploads.
The `govuk_assets:create_whitehall_asset` task can be used to upload any additional files.
---
[Trello card](https://trello.com/c/SFeIQ9Dp/371-serve-hmrc-assets-from-the-asset-manager)
> Add a rake task to upload HMRC PAYE files

- lib/tasks/govuk_assets.rake
The documented list of files does not match the reality.
This also makes it much easier to load all the current files into the asset manager:
```bash
for file in *; do
sudo -udeploy govuk_setenv asset-manager bundle exec rake govuk_assets:create_hmrc_paye_asset[$file]
done
```
---
[Trello card](https://trello.com/c/SFeIQ9Dp/371-serve-hmrc-assets-from-the-asset-manager)
> Do not make assumptions about files in HMRC PAYE task

- app/controllers/whitehall_media_controller.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/models/whitehall_asset_spec.rb
Currently, accessing a soft deleted asset returns a 404.  However, accessing a soft deleted Whitehall asset still attempts to proxy to S3, then returns the resulting XML and 404 proxied back from S3.  This commit changes that behaviour so that soft deleted Whitehall assets are not proxied and a 404 is served from Asset Manager.
Note: the asset media controller uses `find` to get the records, which raises an exception if no records are found.  Whitehall media controller uses `find_by` which does not raise an exception, therefore we have to raise our own exception and rescue with a 404 in the event of no records being returned.
> Return a 404 error when attempting to access a deleted Whitehall asset

- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- lib/tasks/assets.rake
- spec/lib/s3_storage/fake_spec.rb
- spec/lib/s3_storage_spec.rb
This PR adds a Rake task which makes it possible to delete and asset, and remove the asset from S3 if required.
```sh
$ rake assets:delete_and_remove_from_s3[100]
```
Depends on https://github.com/alphagov/govuk-terraform-provisioning/pull/165.
[Trello Card](https://trello.com/c/bod2J0d5/393-make-the-process-of-deleting-assets-off-s3-easier)
> Delete and remove from S3

- app/models/asset.rb
- app/workers/delete_asset_file_from_nfs_worker.rb
When an asset is uploaded, it is stored on disk in a directory named by a hash, like so: `/aa/bb/cccccccccccccccccccccccc`.  The files themselves are deleted after being uploaded to the cloud storage, but the directory is not.
There are lots of things with hashes which start with `aa`.  Fewer but still lots with hashes which start with `aabb`.  Very very few things have the same hash (which is kind of the point!).  So we're creating a lot of directories, which don't get cleaned up.
This wouldn't be so bad if there were more hash collisions, as files are referenced by the full path anyway (not just the hash), so collisions in directory names would be fine.  But because everything (just about) gets a new hash, we're creating a huge number of directories, and directories are not free: I just …
> Delete directory after uploading an asset to S3

- Gemfile.lock
Don't wait for dependabot because this is using a lot of memory right
now.
> Bump govuk_app_config to 1.10.0

- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/requests/access_limited_assets_spec.rb
- spec/requests/access_limited_whitehall_assets_spec.rb
- spec/requests/asset_requests_spec.rb
- spec/requests/media_requests_spec.rb
This stops the test suite outputting various warnings like:
```
DEPRECATION WARNING: The success? predicate is deprecated and will be removed in Rails 6.0. Please use successful? as provided by Rack::Response::Helpers.
```
> Fix success? predicate deprecation warning

- Gemfile
- Gemfile.lock
- Jenkinsfile
- app/controllers/assets_controller.rb
- app/controllers/base_assets_controller.rb
- app/controllers/media_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/models/asset.rb
- config/application.rb
- config/secrets.yml
- spec/controllers/assets_controller_spec.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
- spec/support/authentication.rb
Trello: https://trello.com/c/dawXVwdW/439-asset-manager-files-are-not-available-when-using-access-tokens-or-if-someone-doesnt-have-asset-manager-permission
This is a feature that allows the presence of a token, in either a cookie or a query string, to bypass the authentication needed to view that asset on the draft stack. See https://github.com/alphagov/authenticating-proxy/pull/108 for more info.
This allows the storing of auth_bypass_ids on an asset and allows checking JWT tokens when requesting a draft asset to determine whether the asset should be served or not.
> View draft assets with token authentication

- config/initializers/mime_types.rb
We're currently serving `application/octet-stream` instead which makes Internet Explorer think the files are zip files.
> Add correct mime type for .odp files

- app/controllers/media_controller.rb
- lib/govuk_configuration.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
When an asset is replaced, explicitly use the external host when
redirecting.  Otherwise Rails uses the request host, which may be some
weird internal thing which won't work.
> Redirect to external host when asset is replaced

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
Adding another one results in redirects to '$host//$path', which falls
through to the s3 bucket.
> Asset public URL paths start with a '/'

- db/seeds.rb
This will be used in the e2e tests combined with GDS SSO mock mode to enable authenticated access to the API without needing to pass in a bearer token.
This is based off the one in email-alert-api: https://github.com/alphagov/email-alert-api/blob/master/db/seeds.rb
Once this is merged, it should enable https://github.com/alphagov/travel-advice-publisher/pull/602 to pass correctly.
> Create a database user seed

- app/controllers/media_controller.rb
- config/routes.rb
- spec/controllers/media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/requests/access_limited_assets_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/virus_scanning_spec.rb
https://trello.com/c/xpS0zlU4/803-download-an-attachment-file-through-content-publisher
This ensures we preserve any query params when downloading draft asset, which supports anonymous preview of draft assets via Content Publisher.
> Preserve draft redirect query

- lib/tasks/export.rake
Something should be in the mirrors if:
- it's not been deleted
- it's not been replaced
- it's not been redirected
- it's not a draft
> Add a rake task to export mirrorable assets

- spec/requests/virus_scanning_spec.rb
Trello: https://trello.com/c/hwMoAOau/3-%F0%9F%90%B3-get-all-apps-working-on-docker
This test no longer runs successfully on GDS issued laptops as the ESET
software detects the contents as a virus and quarantines the file, which
is very hard to debug.
This test is also rather strange as it will still pass even if the file
is not identified as having a virus. This is because the endpoint will
return a 404 until a file has been uploaded to cloud storage.
> Remove request test for positive virus scan

- app/controllers/assets_controller.rb
- app/controllers/base_assets_controller.rb
- app/controllers/whitehall_assets_controller.rb
- app/models/asset.rb
- spec/controllers/assets_controller_spec.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/models/asset_spec.rb
- spec/requests/access_limited_assets_spec.rb
Following #677 (which was reverted due to incorrect migrations), this PR aims to support access limiting by organisation id without modifying the existing data schema. 
This PR adds a new field called access_limited_organisation_ids to Asset model to store permitted user organisations.
This also introduces a new parameter `access_limited_user_ids` which maps to `access_limited`
> Support access limits by user organisation id without migrations

- app/controllers/application_controller.rb
- app/controllers/media_controller.rb
- spec/requests/media_requests_spec.rb
Previously the Content Type header was still being set as the asset content type, which caused unexpected behaviour in browsers. Now we return a 403 message to the user and set the content type header to always be set to application/json to render the message.
> Fix forbidden response when downloading assets

- app/controllers/media_controller.rb
- app/models/asset.rb
- spec/controllers/media_controller_spec.rb
- spec/models/asset_spec.rb
**As a** burgeoning fact checker
**I want** to check content related to step by steps and see the assets
**So that** the pages don't look broken
Opens up access to draft assets when the `draft_asset_manager_access` value is present in the JWT payload but will not grant access to draft assets that are marked as access limited to users or organisations.
Asset manager should be aware of a flag which was added in https://github.com/alphagov/collections-publisher/pull/815 that can be set in an auth_bypass_token that allows users access to draft assets.
This is a key part in allowing assets to be available as part of a multi-page fact check. This allows a user access to draft assets they normally wouldn’t have access to.
[Trello card](https://trello.com/c/DoD8SPbI/145-in-asset-manager-allow-an-a …
> Allow an auth bypass token to grant access to all draft assets

- .rubocop.yml
- Gemfile
- Gemfile.lock
- bin/bundle
- bin/create_asset
- bin/rails
- bin/rake
- bin/setup
- bin/update
- bin/update_asset
- lib/tasks/lint.rake
The GOV.UK Lint gem is deprecated in favour of using Rubocop directly
with a set of shared configs.
See https://github.com/alphagov/govuk-rfcs/pull/ 100 for more context.
This adds rake tasks to enable running rubocop.
This also fixes previous linting violations.
> Replace govuk lint with rubocop-govuk

- lib/tasks/lint.rake
rubocop-govuk is only a dev dependency, so this task causes an error when run in production mode:
15:32:26 *** [err :: backend-2.backend.staging.publishing.service.gov.uk] rake aborted!
15:32:26 *** [err :: backend-2.backend.staging.publishing.service.gov.uk] LoadError: cannot load such file -- rubocop/rake_task
> Fix deployment error due to missing rubocop

- app/controllers/application_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
We recently had an issue where an asset was correctly unpublished, but it took manual intervention to remove it from Fastly cache.  Reducing the period that an asset is cached to 30 minutes should mitigate this issue somewhat. 
The intention is to reduce this further, but we want to mitigate the risk of hammering asset-manager too much until we've had sufficient time to test this properly.
> Reduce caching period for assets to 30 minutes

- Gemfile
- Gemfile.lock
We can instead get it from govuk_app_config.
> Remove explicit unicorn dependency

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
We know that, somehow, there are links in the wild to draft assets
which have live replacements.  There doesn't seem much point in
sending people to signon in such cases.
> Redirect draft asset to replacement if replacement is live

- Rakefile
- config/initializers/carrier_wave.rb
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
> Make entire repository pass Rubocop linting

- app/models/asset.rb
- spec/models/asset_spec.rb
Redirecting to replacements is done in media_controller.rb, as the
first thing in the download method:
if asset.replacement.present? && (!asset.replacement.draft? || requested_from_draft_assets_host?)
set_default_expiry
redirect_to_replacement_for(asset)
return
end
In prose, redirection to a replacement happens if and only if these
two requirements are met:
1. The asset has a replacement.
2. The replacement is not a draft (or it is being accessed from the
draft host).
So if a publisher creates a new draft of a document, and replaces some
assets, the live assets won't redirect until the document is published
and the assets become live.  So far so good.
The problem is to do with `asset.replacement`.  When an asset is
replaced, anything which has the original asset as its replacement is …
> Fix transitive redirection breaking with draft assets

- lib/tasks/govuk_assets.rake
It should be looping through the `file_path`s
> Fix HMRC asset upload rake task

- lib/tasks/govuk_assets.rake
This was attempted in d2897ec463e3efdc3139a5c3d94257bc9a46ce31, but didn't
quite correct the bug introduced by the refactor in d2897ec463e3efdc3139a5c3d94257bc9a46ce31.
The original code was `create_or_replace_hmrc_asset(file_path, File.basename(file_path))`,
so I think this commit will fix it for good.
> Fix HMRC .zip upload rake task

- app/models/asset.rb
- spec/models/asset_spec.rb
- spec/requests/virus_scanning_spec.rb
This PR:
* Fixes one broken test locally
* Adds a missing test for directory deletion
* Catches an edge case where the directory can't be deleted, and provides better logging information so we can figure out the root cause
Trello: https://trello.com/c/FDu35RHS/1977-5-investigate-whitehall-sending-blank-file-when-updating-assets
> Provide better logs for "File can't be blank" errors

- app/models/asset.rb
Sometimes we were getting Errno::ENOTEMPTY calls in the `rmdir`
call on the following line, which we attribute to the 'remove_file!'
method being asynchronous.
Code added in 91f19998f1a804ab5839c77d3bd41466d91408e3 allowed us
to see what files exist in the directory after the exception was
raised, but this would return an empty array, suggesting that
whatever file existed to cause the error had since been removed in
the time between the exception being raised and the 'Dir' call.
I won't revert that commit yet in case it provides more useful
information in future errors.
In the current version of carrierwave utilised by Asset Manager,
(0.11.2), the `remove_file!` method deletes the file from disk but
doesn't remove the `file` property from the model, so we can
accomplish the same behaviour …
> Remove file synchronously with FileUtils

- app/models/asset.rb
- spec/models/asset_spec.rb
Prior to this change, we had the equivalent of this:
```
filepath = asset.file.path
FileUtils.remove_file(filepath)
FileUtils.rmdir(File.dirname(filepath))
```
For some reason we [were getting `Errno::ENOTEMPTY` errors][sentry]
being thrown at the `rmdir` call, but despite [logging which
files were in the directory][pr773], it looked as though the
directory was empty.
It isn't clear why the error was being thrown...
1. Perhaps `remove_file` is async
2. Perhaps our `Dir` logging code wasn't doing what we expect
3. Perhaps CarrierWave still held a 'handle' on the file and it
wasn't truly 'deleted' yet?
4. Perhaps there is a hidden file in the dir, beginning with '.'
Either way, there's no reason why we need to be deleting the file
and then its parent directory in this order. There's no risk …
> Delete file and directory in one forced call

- .github/dependabot.yml
- spec/models/asset_spec.rb
In accordance with [RFC 126], we're configuring Dependabot to only
raise Pull Requests for the following three categories:
1. Security updates
2. Internal libraries
3. Framework libraries
Things have moved on slighly since the RFC; we're now using
[GitHub native] configs rather than the legacy `.dependabot`
approach. The syntax is slightly different to the example config
provided in the RFC but most of it is easily transferable.
Security updates (1) [aren't handled by Dependabot config][security].
Rather, they are enabled or disabled per-repository or per-org
through the GitHub UI.
We've handled (2) and (3) in config, and have set it to only raise
PRs for direct updates, i.e. updates to subdependencies of the
named dependencies will not raise PRs.
Trello: …
> Add Dependabot configuration

- .github/dependabot.yml
A follow-on from #786 that fixes:
1. a misconfiguration issue whereby non-named dependencies are still having PRs raised (see #788, #790 and #791)
1. suppresses 'ruby' upgrade PRs, as we have to manually do this in a very specific way. (see #787)
https://trello.com/c/uPoriyfJ/2049-add-dependabot-configuration-to-each-repo-blitz-pair
> Make Dependabot config stricter

- config/initializers/gds_sso.rb
This file is no longer required as the latest release of the gds-sso gem sets these defaults itself ref: https://github.com/alphagov/gds-sso/pull/241
> Remove gds_sso initializer file as it only contains default settings

- lib/tasks/assets.rake
Sometimes the automatic redirection doesn't happen, or an asset needs to be forcibly redirected, and this Rake task should make it easier for people to do.
[Trello Card](https://trello.com/c/14zssUpz/2221-8-investigate-and-fix-whitehall-file-attachments-not-redirecting-%F0%9F%8D%90)
> Add Rake tasks for redirecting assets

- app/controllers/assets_controller.rb
- app/models/asset.rb
- app/presenters/asset_presenter.rb
- spec/controllers/assets_controller_spec.rb
- spec/models/asset_spec.rb
- spec/presenters/asset_presenter_spec.rb
Trello: https://trello.com/c/fHPHwU5H/980-look-into-content-publisher-xss-pdf-issue
This allows a publishing application to specify the content type of an
asset which overrides Asset Manager's default behaviour of using the
filename as a means to determine an asset's content type.
The problem this resolves is when a publishing application decides an
asset is of one type and then Asset Manager disagrees and serves the
file based on the extension - for example if someone (oddly) uploaded a
PDF with a ".html" extension. This issue could cause a confusing error
experience for users and could potentially lead to security issues
of spoofing types of documents.
In considering the application of this I did wonder whether Asset
Manager should just be changed to determine content type based off …
> Permit publishing applications to specify a content type

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
This applies a fix for handling the situation where an assets
content_type is nil. In these situations we should fallback to
determining the content type from the files extension.
When a content_type of nil is returned Rails will set this to text/html
and this will cause the response to be misrendered for other content
types.
I'm a bit concerned about the level of mocking in the integration test
for this makes this more of a unit test, however my quick attempts to
unpick this weren't fruitful.
Before:
After:
> Fix missing content_type headers

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
An aspect of this app I found rather head scratching is that it returns
a `head :ok` even when a response is fresh and a file isn't
sent. From an investigation I learnt that later in the Rack middleware
this 200 response is being converted into a 304 [1] implicitly. This causes
some confusion where the Rails log thinks it's returned a 200 whereas the
app has actually returned a 304.
For example this is the Nginx vs Rails log for the same request:
January 21st 2021, 20:59:02.440 200 GET /government/uploads/system/uploads/default_news_organisation_image_data/file/159/s300_HCA_sign.JPG HTTP/1.0 asset-manager
January 21st 2021, 20:59:02.000 304 GET /government/uploads/system/uploads/default_news_organisation_image_data/file/159/s300_HCA_sign.JPG HTTP/1.1 assets-origin-json.event.access
To try …
> Return not_modified headers from MediaController

- lib/tasks/assets.rake
If we end up with a path for an asset's `redirect_url`, then Rails
fills in its hostname, and so redirects to `assets-origin....`, which
is only accessible on the VPN.
Rather than implement a work-around in the asset controller, instead
just require that a full URL be given.
> Raise an error if a path is given for a redirect_url

- .dockerignore
- .github/workflows/ci.yaml
- Dockerfile
- config/puma.rb
Install dependencies in an intermediate builder stage before copying output to final image
Some steps have been dropped like healthcheck and PORT and MONGODB_URI as not needed for build.
Also replace foreman with puma.
https://trello.com/c/pRBFWfGx/688-asset-manager-replatforming
> Update Dockerfile to streamline it

- app/controllers/whitehall_assets_controller.rb
- spec/controllers/whitehall_assets_controller_spec.rb
- spec/controllers/whitehall_media_controller_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
Some foundational work to allow shareable previews for Whitehall to access assets - Whitehall has its own create endpoint, so this PR adds auth_bypass_id (a UUID that allows for non-sign-on access to an edition and its related content via a token) to the allowed parameters for Whitehall assets. This is identical to what is done for non-Whitehall assets.
This commit also introduces some tests for the WhitehallMediaController to ensure that an asset can be accessed with an access token containing an auth_bypass_id. This repeats some tests in the non-Whitehall media controller, and the behaviour is already defined for the WhitehallMediaController via inheritance, but I thought the tests were useful from a documentation standpoint.
> Add auth bypass id to whitehall endpoint

- app/controllers/whitehall_assets_controller.rb
- spec/controllers/whitehall_assets_controller_spec.rb
Trello: https://trello.com/c/CXTgjI76/383-look-at-sidekiqjobretryskip-errors-logged-to-sentry
The Whitehall legacy_url_path is not a unique identifier for an asset
and there can be one that is current and multiple ones from the past
that are deleted.
The method to look up an asset relied on updated_at to determine which
asset is most-recent. As updated_at is an automatically changed
attribute this is risky as any misguided manipulations of models can
cause this to change and then mean that attempts to look up a current
item fail due to a deleted item taking precedence.
Looking into the database I found 260 assets with this problem (which is
a tiny percentage of the overall number of assets but enough to indicate
the logic assumption wasn't strong enough).
This issue can cause Asset …
> Don't rely on updated_at to determine whether asset is deleted

- Dockerfile
There is no need for Freshclam daily updates to log to a separate log file as we already run it a s background process with logging to STDOUT.
`freshclam -d --stdout --foreground`
Also adding new user with ID 1001 and GID 1001
> Stopping Freshclam from writing separate log file and adding app user

- Dockerfile
This should allow writing to /app/tmp directory and fix the current permission denied errors
in EKS.
This is part of non-root container work:
https://trello.com/c/Jef1t4xU/903-fix-app-permission-errors-due-to-nonroot
> Adding softlink to /tmp filesystem.

- config/routes.rb
- lib/healthcheck/cloud_storage.rb
- lib/s3_storage.rb
- lib/s3_storage/fake.rb
- spec/lib/healthcheck/cloud_storage_spec.rb
- spec/lib/s3_storage_spec.rb
This PR adds a healthcheck that checks for connectivity with the s3 bucket, as part of work to improve checks before enabling continuous deployment for the app.
It uses the head_bucket method from the aws s3 api, which returns a successful response if the bucket requested exists and the requester has access to it. In the case where we get this successful response, we return a GovukHealthcheck::OK response.
We return a GovukHealthcheck::CRITICAL status in the following cases:
* an error is raised by the call to head_bucket
* head_bucket returns an unsuccessful response
This is because there is some ambiguity in the [documentation](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#head_bucket-instance_method) vs observed behaviour, so we want to protect against both cases. …
> Add healthcheck for connectivity with S3 bucket

- lib/tasks/assets.rake
- spec/rails_helper.rb
- spec/tasks/assets_tasks_spec.rb
The ClassificationFeaturingImageData model was renamed in Whitehall, and this is used on the fly to generate the asset url, meaning that when a topical event was republished, its asset urls pointed to the new location (/topical_event_featuring_image_data) rather than the legacy url those assets are currently found at (/classification_featuring_image_data). This temporary rake task fixes this issue by updating all the legacy url paths for classsification_featuing_image_data to be topical_event_image_data. 
A long term fix for this would be to store the image urls in Whitehall, so they are not dynamically generated each time. But this is an immediate fix these document types for now.
The fix flow should be - run this task, and then republish all topical events immediately. …
> Add a temporary task to update the legacy urls for topical event assets

- app/models/asset.rb
- spec/models/asset_spec.rb
- spec/requests/asset_requests_spec.rb
If we receive a request [1] to create an asset, and then very quickly after that receive a request [2] to redirect the asset (i.e. the asset is changed in a publishing app, resulting in a new asset being created and the existing asset redirecting to the new asset), we can receive a `StateMachine:InvalidTransition` error.
This is because a concurrency issue to do with what happens when an asset is saved. We have an after save callback which a) schedules a virus scan if the asset is unscanned, which b) marks the asset as clean when this virus scan is complete and passes.
When we receive a create [1] and redirect [2] in short succession, the following happens:
1) we receive request [1] and schedule a virus check since the asset is unscanned
2) we receive request [2] and schedule a virus …
> Don't virus scan when redirect url is present

- Dockerfile
- Install clamdscan package, which was missing.
- Patch the config files for clamd and freshclam to fix logging and permissions.
- Avoid installing shared-mime-info package twice, as it doesn't seem to be needed in the build stage.
- Fix a couple of Dockerfile lints.
Really we want ClamAV to run as a separate service so that we can sandbox it more restrictively and run it with the absolute minimum of privileges, but we'll tackle that in another PR.
This change only affects Kubernetes/Docker and not EC2 (i.e. current production).
Tested: ran locally in Docker:
```
$ docker build -t asset-manager
...
$ docker run -it -v clam-sigs:/var/lib/clamav asset-manager bash
app@242503f4a4c4:~$ clamd &
...
app@242503f4a4c4:~$ clamdscan Gemfile
/app/Gemfile: OK
app@242503f4a4c4:~$ cat >eicar.txt …
```
> Fix clamdscan in container image. 

- .dockerignore
- Dockerfile
- config/initializers/carrier_wave.rb
Essentially the same change as https://github.com/alphagov/whitehall/commit/3d13ac8.
This only affects running in Docker / Kubernetes. No change in EC2 / current production.
Also some minor cleanup in `.dockerignore` while we're there.
Tested: [deployed to integration](https://github.com/alphagov/asset-manager/actions/runs/3410602597) and was able to [create an asset](https://github.com/alphagov/asset-manager/blob/main/docs/api.md#create-an-asset).
> Avoid writing to the image filesystem by default.

- Dockerfile
Turns out it's not really worth doing this, since nobody would want to run with this config anyway. We replace the whole of `/etc/clamav` via a configmap when running in k8s, and that's part of the Helm chart so there's no real portability issue here.
Patching this config in the Dockerfile just adds a potential source of confusion.
Instead let's just remove the default configs for ClamAV, since those won't work properly in a container.
Partially reverts 575363a.
Also avoid setting `GOVUK_UPLOADS_ROOT`, as it makes more sense to do that in the Helm chart, where we're configuring the volumeMount that it uses.
https://trello.com/c/moEiT5BG
> Stop patching `/etc/clamav/*.conf` in the container build.

- docs/api.md
- Illustrate how to use a bearer token with `curl`. This is sometimes useful when troubleshooting.
- Add a paragraph break between the point about return format and the point about authentication.
- Remove unnecessary use of `echo` in commands for creating temporary files.
> Minor improvements to examples in API docs.

- Gemfile.lock
This should stop us from getting noisy Puma errors logged to sentry
[Trello](https://trello.com/c/OLZZoNNI/597-handle-pumahttpparsererror-errors-in-sentry)
> Bump version of govuk app config

- Gemfile
- Gemfile.lock
Bumping carrierwave to version 3.0 caused an error [1] in Sentry. It is not clear whether any of the breaking changes in v3 have caused this, nor how long it would take to debug and fix the incompatibilities.
The Whitehall asset management team have pinned carrierwave to v2, and they have on their roadmap to look at the future of using carrierwave in whitehall [2].
They've pointed out that whitehall's use of carrierwave is more complex than asset-manager's, so the issues may be unrelated, but I still think there's value in coordinating our versions.
[1] Details in the PR that reverted the bump https://github.com/alphagov/asset-manager/pull/1152
[2] https://github.com/alphagov/whitehall/pull/8007
This application is owned by the publishing platform team. Please let us know in …
> Pin Carrierwave gem at version 2

- spec/service_consumers/pact_helper.rb
This change is added so that the new pact test introduced inside `gds-api-adapter` for `/media/{id}/{filename}` is able to run correctly refer `https://github.com/alphagov/gds-api-adapters/pull/1211#issue-1892210198`
> Added pact provider state for `/media/{id}/{filename}`

- app/controllers/media_controller.rb
- spec/controllers/media_controller_spec.rb
- spec/lib/s3_storage/fake_spec.rb
- spec/requests/access_limited_assets_spec.rb
- spec/requests/access_limited_whitehall_assets_spec.rb
- spec/requests/media_requests_spec.rb
- spec/requests/virus_scanning_spec.rb
- spec/requests/whitehall_media_requests_spec.rb
- spec/service_consumers/pact_helper.rb
In local development using govuk-docker, we want to be able to preview Assets in Whitehall - this means rather than relying on Nginx we need to use a redirect to serve assets. The cloud-storage-proxy does not work in local env because of using fake s3, which serves the assets from the local file system.
We have also had to change the virus scanning tests to match the new behaviour. 
This PR is dependant of https://github.com/alphagov/govuk-docker/pull/685. Please make sure to update govuk-docker.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull …
> Fix static URL for assets (local dev env)

- app/controllers/media_controller.rb
- app/models/asset.rb
- app/models/whitehall_asset.rb
- spec/controllers/media_controller_spec.rb
- spec/models/asset_spec.rb
- spec/models/whitehall_asset_spec.rb
Previous behaviour separated whitehall assets from regular assets by implementing a boolean check (mainstream?) which was false for whitehall assets.
We are changing the behaviour of assets in whitehall, so that all assets (unless already published) will use the non-legacy download endpoint. 
The underlying reason is that whitehall is moving away from using `legacy_url_path` for identifying assets, therefore the media endpoints need to work for whitehall assets too. 
[Trello card here](https://trello.com/c/UC1jt0TH/179-assetmanager-should-be-able-to-serve-whitehallassets-from-asset-download-endpoints)
> Enable serving whitehall asset from media download endpoint

- app/models/asset.rb
- app/workers/virus_scan_worker.rb
https://trello.com/c/9YZ5VItp
We have an ongoing issue where we are seeing the following errors related to missing files coming from the VirusScanWorker:
- Errno::ENOENT: No such file or directory
- StateMachines::InvalidTransition: Cannot transition state via :scanned_clean from :unscanned (Reason(s): File can't be blank)
Assets should go through the following stages:
1. unscanned => saved to the file system and scanned by ClamAV in a background job.
2. scanned  => Saved to AWS.
3. uploaded => removed from the file system.
However, it seems like the file has already been removed during the virus scanning stage.
This adds logging so that we can trace the history of assets which raise the above errors to try to diagnose the issue.
---
This application is owned by the publishing platform …
> Add logging to help diagnose ongoing issue with virus scanning

- Dockerfile
Currently adding latest version found on https://www.clamav.net/downloads
As a todo:
Can improve this by using curl to ascertain the latest release then
injecting that as variable `$LATEST` rather then hardcoding the current
version.
Thus the wget line will change to:
` wget https://www.clamav.net/downloads/production/clamav-$LATEST.linux.x86_64.deb`
https://trello.com/c/TicAq9G1/1238-update-clamav-engine-to-latest-version
> Updating ClamAV engine with offical version 1.2.1

- app/models/asset.rb
- app/workers/virus_scan_worker.rb
- spec/workers/virus_scan_worker_spec.rb
Asset attempts to read metadata of the file every time the asset is saved. This seems to lead in error in production as the below stack trace shows. It looks like several processes attempt to change the state of the asset at the same time, some of the processes remove the actual local file which then causes the subjequent processes to fail reading the local file.
In any case, reading the local file should be necessary only rarely - not every time when Asset state is modified. This pr attempts to minize the reads.
It also looks like in production VirusScannerWorker gets executed several times at the same time on the same asset. I don't know why this happens, but this pr attemps to avoid unnecessary state transition from the VirusScanner, if another process has already taken over the state …
> Attempt to avoid some of the Enoent issues

- Gemfile
- Gemfile.lock
- app/workers/virus_scan_worker.rb
- config/initializers/sidekiq.rb
- spec/workers/virus_scan_worker_spec.rb
This will prevent multiple jobs becoming enqueued for a single asset until the original job has finished executing.
We are currently seeing an issue where a user can replace the file after uploading but before the virus scan has completed. This results in a second virus scan being enqueued, which subsequently fails as the asset has been deleted from the filesystem. This should prevent that from happening.
[Trello card](https://trello.com/c/UWS9qEtj)
> Constrain `VirusScanWorker` to one concurrent worker per asset

- app/models/asset.rb
It looks like the validation rule that expects a file to be present is not working well in production where there are several instances of Asset Manager and there are several concurrent processes trying to update the asset metadata.
This PR would make it so what the only time we really need the file to be a required field is when we're creating a new asset.
Whitehall is getting a number of  HTTP 422 from Asset Manager.
[sentry](https://govuk.sentry.io/issues/4586734135/?alert_rule_id=9401721&alert_type=issue&environment=production&notification_uuid=616583c4-a0fe-47e6-bcf8-46833b9d8ae3&project=202259&referrer=slack)
> Only require file to be set when creating a new instance of the Asset

- Gemfile.lock
This was removed from the Gemfile.lock during [the Ruby 3.3 update](https://github.com/alphagov/asset-manager/commit/90209aa81deb9b58f77441207ed1bb34decd99a2) but not removed as an actual dependency, therefore any subsequent runs of `bundle install` have resulted in the incompatible version of the gem being reinstalled.
Therefore upgrading to a version of `google-protobuf` that is compatible with Ruby 3.3.
> Bump `google-protobuf` to 3.25.3

- docs/api.md
- docs/authorisation.md
I've been attempting to rationalise the handling of attachment assets in Whitehall. To do that I needed to understand what some of the parameters Whitehall includes in the requests that it sends to Asset Manager do. I found that there wasn't any documentation describing those parameters, so I thought I would add some. Let me know if there are any inaccuracies.
I did think about including this documentation within the API document, but the way that is formatted at the moment doesn't lend itself brilliantly to describing individual keys within a request body, so I went for a separate doc in the end.
> Added some documentation of the various authorisation options available for assets

- config/initializers/sidekiq.rb
Currently, we get spammed by Sidekiq unique jobs logs when running the test suite.
Disable logs in testing as described here
https://github.com/mhenrixon/sidekiq-unique-jobs?tab=readme-ov-file#uniqueness.
---
> Disable Sidekiq unique jobs logger in testing

- app/models/asset.rb
- spec/models/asset_spec.rb
https://trello.com/c/4PkYkOal
Asset metadata is not being updated when an asset is uploaded with a file which
has the same name as the previous file. This is because of a condition added in
#1258 that was intended to quieten some errors we were seeing at the time. This
same issue was addressed in #1263.
This is problematic as there is a guard statement in the S3 uploader that
prevents assets with an unchanged MD5 hexdigest from uploading.
---
> Ensure asset metadata is updated when file name isn't changed

- .github/workflows/deploy.yml
- Dockerfile
This starts running asset-manager builds through the multi-arch workflow so we get ARM builds for use with our Graviton-based nodes.
> Start building asset-manager for ARM.

- .github/workflows/deploy.yml
At present, the build is tightly coupled to an x86_64 version of ClamAV. In order to un-break the builds, we're going to keep Asset Manager on x86 until we can decouple ClamAV from the build.
> Unblock Builds, need to unbundle ClamAV soon

- Dockerfile
This adds another build stage for the Docker Build process so we can bundle a natively compiled version of ClamAV for the respective architecture and version of Ubuntu that our Ruby apps are built on.
For some odd reason, Cisco builds separate ARM images of ClamAV but does not provide up to date ARM-supported packages via APTitude. This way, we can build and bundle a version of ClamAV that we know is going to work with our app, regardless of which platform we are trying to launch it on.
The original plan was to spin ClamAV into a "sidecar" container but this still would have required a local copy of `clamdscan` and so this approach would not have worked-around or solved the problem of suitable pre-compiled binaries not being available.
> Build and Bundle ClamAV to get Native Containers

- .github/workflows/deploy.yml
Now we've (theoretically) fixed the Dockerfile to build for ARM and AMD, we should switch back to the multi-build workflow.
> Re-enable the multi-arch build process

- Dockerfile
Switching to Ubuntu 24 to align with the base images. Also, the `netcat` package needs to be switched to `netcat-traditional` in this version of Ubuntu.
> Netcat package has been renamed in Ubuntu 24

- Dockerfile
This just changes the location that we pull the ClamAV Source from - the Clam AV Mirror has very aggressive rate-limiting in place that appears to be failing our builds.
It's possible that by sharing the Github runners, we're coming across the rate limit more often than we'd expect.
> Avoid the ClamAV Mirror Rate Limit

- Dockerfile
We are encountering some permission errors in the Freshclam jobs:
```
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: initialize: libfreshclam init failed.
ERROR: Initialization error!
ERROR: Can't open /var/log/clamav/freshclam.log in append mode (check permissions!).
```
These permission errors are related to the `/var/log/clamav` directory. In Cisco's Debian Dockerfile, they do this:
```bash
install -d -m 755 -g "clamav" -o "clamav" "/var/log/clamav" && \
```
So let's do something similar for ours, except use the `app` user and group.
> Attempt permission fix for Clam AV Logs Directory

- Dockerfile
Shouldn't matter much but might as well keep this consistent (both with what we used to install under 22.04 and with what's in govuk-infrastructure/toolbox).
The OpenBSD implementation lacks `-e` (which is a plus) and is a bit more modern and actively maintained.
netcat is used in the [healthcheck script](https://github.com/Cisco-Talos/clamav-docker/blob/main/clamav/1.3/debian/scripts/clamdcheck.sh) in the underlying clamav container.
> Trivial: standardise on netcat-openbsd.

- Dockerfile
The new build process leaves the various ClamAV binaries in `/usr/bin`, whereas they were previously linked to `/usr/local/bin`. Let's symlink these binaries so they can still be found in the right place by Asset Manager.
> Symlink the new AV path to avoid breakages.

- Dockerfile
This changes the clam configuration files to try and run the Clam services as the "app" user in the container to try and avoid any permissions problems being experienced. This may explain why we are getting permissions issues when freshclam is trying to run in integration.
Also set the permissions for the symlinks in /usr/local/bin to match the permissions elsewhere (the ones we created seem to default to 0777).
> Build ClamAV to run as "app" user for container.

- Dockerfile
This switches the default Log file paths for the ClamAV config files to `/dev/stdout` to allow ClamAV to try and function in an unprivileged environment. Some other changes will be going into the Helm Chart to add some extra args to the `freshclam` command.
> Set all Log File paths to Stdout for ClamAV

- Dockerfile
The config path appears to be embedded in the clamav binaries, and it wasn't pointing to where we're putting our config files. This seems to fix it (tested uploading a PDF to whitehall in integration)
> Set correct config directory when building clamav

- Dockerfile
- lib/govuk_configuration.rb
- lib/virus_scanner.rb
- spec/lib/govuk_configuration_spec.rb
- spec/lib/virus_scanner_spec.rb
- Use govuk-ruby-builder for clamav. Simplifies the Dockerfile by eliminating boilerplate and speeds up the build by not having to install a bunch of stuff that already ships with govuk-ruby-builder.
- Don't run the clamav Python testsuite; it's super slow and we're building from an official source tarball with a very common config, so it's not worth blowing up asset-manager's build time.
- Add a crude but fast and somewhat effective smoke test for the two clam binaries that asset-manager needs.
- Use the system Rust instead of faffing about installing it ourselves, since we don't antipcate any need to run on PowerPC any time soon.
- Remove a bunch of unneeded Apt packages.
- Remove some unneeded workarounds, e.g. install the clam binaries in the desired directory (which happens to be the …
> Simplify and speed up the clamav build.

- app/models/asset.rb
- app/workers/delete_asset_file_from_nfs_worker.rb
- config/brakeman.ignore
- spec/models/asset_spec.rb
The [SaveToCloudStorageWorker](https://github.com/alphagov/asset-manager/blob/5d410e5f5c6680eeb5836011313a811485390cbe/app/workers/save_to_cloud_storage_worker.rb#L3) is kicked off as soon as virus scanning is complete and [the asset transitions to the clean state](https://github.com/alphagov/asset-manager/blob/f5f9c1a06b5d1a47d8c84227678b3ddea25bc94c/app/models/asset.rb#L97-L99).
When the SaveToCloudStorageWorker completes the upload, it [triggers the upload_success event](https://github.com/alphagov/asset-manager/blob/5d410e5f5c6680eeb5836011313a811485390cbe/app/workers/save_to_cloud_storage_worker.rb#L10), which [transitions to the uploaded state](https://github.com/alphagov/asset-manager/blob/f5f9c1a06b5d1a47d8c84227678b3ddea25bc94c/app/models/asset.rb#L105-L107).
There's an …
> Fix race condition where file is deleted while updating assets

- lib/s3_storage.rb
- spec/lib/s3_storage_spec.rb
At the moment, we create new AWS clients whenever we download or head an object. Each time we do this, the client requests a new set of AWS credentials using the pod's (or the node's?) metadata endpoint.
This causes a problem when asset-manager is under high load, because the AWS metadata endpoint has a rate limit. Eventually, we start getting 429 errors back from the metadata endpoint, which the AWS client reports as:
Aws::Sigv4::Errors::MissingCredentialsError: missing credentials
(At least according to issue #2823 in aws-sdk-ruby)
We see this as a spike of 500 errors every night when the mirror script runs:
The `S3Storage` instance in asset-manager is created once when the app loads, and set as `Services.cloud_storage`. In other words it's effectively a singleton - the same instance …
> Reuse AWS client between S3 requests

- lib/tasks/assets.rake
- spec/lib/tasks/assets_spec.rb
It seems unnecessarily laborious to have to run rails console commands (https://docs.publishing.service.gov.uk/manual/manage-assets.html#get-an-assets-id) in order to know what to pass to a rake task
(https://docs.publishing.service.gov.uk/manual/manage-assets.html#redirect-an-asset).
It should just be a rake task.
> Add `assets:get_id_by_legacy_url_path` rake task

- app/models/asset.rb
- spec/controllers/assets_controller_spec.rb
- spec/models/asset_spec.rb
There are over 1000 assets in the Asset Manager database which are not drafts, but have a parent document URL that points to the draft stack. Whilst this doesn't seem to break anything, that shouldn't really be possible so it would seem to make sense to apply some validation.
We expect this may help us to diagnose an issue where at least some of those 1000+ assets were unexpectedly made public ahead of their parent document being published. If this validation had been in place we think it would have prevented the issue.
I'm not really sure that we should be keeping parent document URLs in Asset Manager as it seems like a rather circular relationship, but anyway, it might prove useful in this case!
> Validate public assets have public document URLs

- app/models/asset.rb
- spec/models/asset_spec.rb
`File.stat(path)` raises `Errno::ENOENT` if the file does not exist.
In the case that a file has already been deleted (e.g. by another worker), we don't need to raise an error, just fail gracefully.
Therefore only attempting to load the file if it actually exists.
Also adds a test that covers the behaviour that caught this issue: attemting to soft-delete a file that has already been removed from the filesystem.
[Trello card](https://trello.com/c/gRpytEO7)
> Do not attempt to open file if it does not exist

- Gemfile
This gem is being installed in the `development` environment, meaning it runs when using the application locally, resulting in jobs not actually getting enqueued.
Moving it to be `test` only, since that is the only time it is actually needed.
[Trello card](https://trello.com/c/knx2tuL4)
> Move `rspec-sidekiq` to test group

- README.md
- config/routes.rb
This makes the Sidekiq UI available to developers with production access.
This has been implemented in the same way as in [Publishing API](https://github.com/alphagov/publishing-api/pull/2839), albeit also adding the options for `sidekiq-unique-jobs` that is used by this application.
[Trello card](https://trello.com/c/knx2tuL4)
> Add Sidekiq user interface

- app/sidekiq/delete_asset_file_from_nfs_job.rb
- app/sidekiq/save_to_cloud_storage_job.rb
- app/sidekiq/virus_scan_job.rb
The workers were renamed in https://github.com/alphagov/asset-manager/pull/1493, but some jobs were already enqueued with the old names.  Therefore temporarily adding the old names as aliases until they have been processed.
This is the suggestion in the [Sidekiq FAQs](https://github.com/sidekiq/sidekiq/wiki/FAQ#how-do-i-safely-rename-a-worker).
[Trello card](https://trello.com/c/K9ds4XZX)
> Add aliases for renamed Sidekiq jobs

- lib/tasks/assets.rake
This is part of running a clean-up on assets that should be deleted, according to Whitehall.
Since `Attachments` and `AttachmentDatas` are already dealt with on the Whitehall side, we can just soft delete the corresponding `Assets` in Asset Manager.
We discovered a set of assets that have an invalid deleted state, most likely from older code logic. These are giving a "State is invalid" error. We're resetting them to "uploaded" state in order to pass validation. 
FYI: There are around 600 assets in this invalid state, but they were not flagged up for deletion on our side. Work to fix these is articulated in this card [here](https://trello.com/c/qKfXumZ2/633-fix-bug-where-asset-manager-state-is-deleted).
[Trello](https://trello.com/c/66WfDvAU/3130-delete-assets-that-are-marked-as-deleted-in- …
> Add temproary soft delete bulk rake task

- lib/tasks/assets.rake
- spec/lib/tasks/assets_spec.rb
Multiple Zendesk tickets related to `whitehall` assets being live when they should not be, triggered an analysis of the problematic data - PR [here](https://github.com/alphagov/whitehall/pull/9351). We've already deleted a batch of assets that `whitehall` expected to be deleted but they were not, using [this rake task](https://github.com/alphagov/asset-manager/pull/1543). We have now investigated asset deletion states further, and we've produced [a set of assets](https://drive.google.com/file/d/1Baqsq3p_xstzSkZYMmgC1w6prJ_GqCs3/view?usp=drive_link) that, despite not being deleted in Whitehall, should not be live. In order to preserve some data integrity, we're choosing to fix the data with this rake task, rather than do a mass deletion. The assets in question are serving a chain of only …
> Add bulk fix assets rake task

- docs/asset_state_machine_overview.md
Add summary of asset fields. This captures what we've learned during the asset deletion investigation.
Opened on the back of [this other PR](https://github.com/alphagov/govuk-developer-docs/pull/4866).
[Trello](https://trello.com/c/YIs8YZmF/3146-fix-live-assets-on-superseded-editions)
> Add documentation - overview of asset fields

- config/brakeman.ignore
A file was renamed in a1ead6a827f80dbf0c4c030626edac8ebda62c1d but the corresponding entry in the brakeman ignore file was not updated.
Therefore updating to stop the warning being raised, even though we previously intended for it to be ignored.
[Trello card](https://trello.com/c/p1A4ztJl)
> Update brakeman ignore filename and fingerprint

- app/controllers/assets_controller.rb
- spec/controllers/assets_controller_spec.rb
In publishing apps (Whitehall), we have the following issue:
1. User replaces an attachment asset with a new one on a new edition of a published document.
2. User deletes the attachment.
3. User publishes the new edition of the document.
4. Replaced attachment asset remains live.
This happens because the deleted asset still has a value of "false" for the draft attribute, so the replacement on the old asset is not active. 
Since the user has deleted the attachment (in the publishing app), they are unlikely to become aware of the issue of the original asset remaining live. Because documents can have replacements across multiple editions, one such unintended live asset implicitly causes all the replaced assets pointing to it to implicitly remain live, providing outdated information to the …
> Allow updates to draft deleted assets
